# SPDX-FileCopyrightText: 2026 Sebastien Rousseau
# SPDX-License-Identifier: Apache-2.0 OR MIT
"""smoke-install-safety.py reports a deleted prompt file, rather than crashing on it.

The smoke test compares the user's CLAUDE.md with its original bytes after
each install. When an install deleted the file -- the regression the
comparison exists to catch -- filecmp raised FileNotFoundError, so the gate
showed a traceback instead of naming the broken property. The installer is
faked here, so each case is about the smoke test's own reporting.
"""

from __future__ import annotations

import io
import json
import shutil
import subprocess
import tarfile
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from .support import load_script, run_main

GENERATED = "<!-- Generated by AgtMLS -->\n"


class DeletedPromptTests(unittest.TestCase):
    def setUp(self) -> None:
        self.module = load_script("smoke-install-safety.py")

    def run_with(self, deletes_on: str) -> tuple[int, str]:
        """An installer that behaves, except that one mode deletes CLAUDE.md."""

        def install(target: Path, *flags: str) -> subprocess.CompletedProcess:
            prompt = target / "CLAUDE.md"
            mode = next((f for f in ("--dry-run", "--skills-only", "--force") if f in flags), "plain")
            if mode == deletes_on == "--force":
                (target / "CLAUDE.md.agtmls-backup.1").write_bytes(prompt.read_bytes())
                prompt.unlink()
                return subprocess.CompletedProcess([], 0, "")
            if mode == deletes_on:
                prompt.unlink()
                return subprocess.CompletedProcess([], 0 if mode != "plain" else 1, "[dry-run]\n")
            if mode == "--dry-run":
                return subprocess.CompletedProcess([], 0, "[dry-run] plan\n")
            if mode == "--force":
                (target / "CLAUDE.md.agtmls-backup.1").write_bytes(prompt.read_bytes())
                prompt.write_text(GENERATED, encoding="utf-8")
                return subprocess.CompletedProcess([], 0, "")
            if mode == "--skills-only":
                return subprocess.CompletedProcess([], 0, "")
            ours = prompt.exists() and "Generated by AgtMLS" in prompt.read_text(encoding="utf-8")
            return subprocess.CompletedProcess([], 0 if ours else 1, "")

        refused = subprocess.CompletedProcess([], 1, "unknown agent\n")
        real_run = subprocess.run

        def run(argv, **kwargs):
            if argv[0] == "git":
                return real_run(argv, **kwargs)
            return refused

        with mock.patch.object(self.module, "install", side_effect=install), \
                mock.patch.object(self.module.subprocess, "run", side_effect=run):
            return run_main(self.module)

    def test_an_intact_installer_passes(self) -> None:
        code, output = self.run_with(deletes_on="none")
        self.assertEqual(code, 0, output)

    def test_a_refusal_that_deletes_the_prompt_is_reported(self) -> None:
        code, output = self.run_with(deletes_on="plain")
        self.assertEqual(code, 1, output)
        self.assertIn("FAIL: install modified a prompt file it did not generate", output)

    def test_a_dry_run_that_deletes_the_prompt_is_reported(self) -> None:
        code, output = self.run_with(deletes_on="--dry-run")
        self.assertEqual(code, 1, output)
        self.assertIn("FAIL: --dry-run modified the prompt file", output)

    def test_a_force_install_that_leaves_no_prompt_is_reported(self) -> None:
        code, output = self.run_with(deletes_on="--force")
        self.assertEqual(code, 1, output)
        self.assertIn("FAIL: --force did not write the generated prompt", output)

    def test_skills_only_that_deletes_the_prompt_is_reported(self) -> None:
        code, output = self.run_with(deletes_on="--skills-only")
        self.assertEqual(code, 1, output)
        self.assertIn("FAIL: --skills-only removed a prompt file it did not generate", output)


if __name__ == "__main__":
    unittest.main()


class MakeInstallStatsTests(unittest.TestCase):
    """smoke-make-install.py reads the installed binary's `stats --json`."""

    def setUp(self) -> None:
        self.module = load_script("smoke-make-install.py")

    def stats(self, stdout: str) -> list[str]:
        answer = subprocess.CompletedProcess([], 0, stdout)
        with mock.patch.object(self.module.subprocess, "run", return_value=answer):
            return self.module.stats_problems(Path("/opt/bin/agtmls"))

    def test_a_stats_answer_that_is_not_an_object_is_reported_not_raised(self) -> None:
        """payload.get() raised AttributeError on a JSON list or string."""
        for stdout in ("[]", '"stats"', "7"):
            with self.subTest(stdout=stdout):
                self.assertEqual(self.stats(stdout), [f"installed binary's stats is not a JSON object:\n{stdout}"])

    def test_a_good_stats_answer_passes(self) -> None:
        version = self.module.json.loads(
            (self.module.ROOT / ".claude-plugin" / "plugin.json").read_text(encoding="utf-8")
        )["version"]
        self.assertEqual(self.stats(json.dumps({"registry_version": version, "skills": 3})), [])


class ExportArchiveTests(unittest.TestCase):
    """smoke-export.py reads each export's manifest out of its archive."""

    def setUp(self) -> None:
        self.module = load_script("smoke-export.py")
        self.tmp = Path(tempfile.mkdtemp(prefix="agtmls-export-archive-"))
        self.addCleanup(shutil.rmtree, self.tmp, True)

    def archive(self, manifest: str | None) -> list[str]:
        members = {"agtmls/ADAPTERS.md": "x", "agtmls/skills/using-agtmls/SKILL.md": "x"}
        if manifest is not None:
            members["agtmls/export-manifest.json"] = manifest
        with tarfile.open(self.tmp / "agtmls-openai-minimal.tar.gz", "w:gz") as tf:
            for name, text in members.items():
                data = text.encode()
                info = tarfile.TarInfo(name)
                info.size = len(data)
                tf.addfile(info, io.BytesIO(data))
        exported = subprocess.CompletedProcess([], 0, "")
        errors: list[str] = []
        with mock.patch.object(self.module.subprocess, "run", return_value=exported):
            self.module.check_archive("openai", "minimal", [], self.tmp, errors)
        return errors

    def test_an_archive_without_its_manifest_is_reported_not_raised(self) -> None:
        """extractfile raised KeyError for a member the archive does not have."""
        errors = self.archive(None)
        self.assertIn("openai/minimal archive missing agtmls/export-manifest.json", errors)
        self.assertIn("openai/minimal cannot read export manifest", errors)

    def test_a_manifest_that_is_not_a_json_object_is_reported_not_raised(self) -> None:
        for text, reason in (("{nope", "is not valid JSON"), ("[]", "is not a JSON object")):
            with self.subTest(manifest=text):
                errors = self.archive(text)
                self.assertTrue(any(e.startswith(f"openai/minimal export manifest {reason}") for e in errors), errors)
