# SPDX-FileCopyrightText: 2026 Sebastien Rousseau
# SPDX-License-Identifier: Apache-2.0 OR MIT
"""The doctor and the provider installer, driven against a cut-down registry.

Both are what a person runs when something is already wrong, so a branch
that never executes is a diagnosis nobody has seen. DoctorTests in
test_generators.py proves the doctor passes a healthy checkout and notices a
missing document; these cover the rest of what it claims to check -- the
plugin manifest, eval coverage, the gate it re-runs, and a consumer target in
every state an install can leave it in.
"""

from __future__ import annotations

import json
import shutil
import tempfile
import unittest
from pathlib import Path

from .mini_registry import SKILLS, mini_registry, replace_file
from .support import load_script, retarget, run_main

_WORKSPACE: str = ""
FIXTURE = Path()
GENERATED = "<!-- Generated by AgtMLS -->\n# Prompt\n"


def setUpModule() -> None:
    # One registry for the module: every test that edits it restores it.
    global _WORKSPACE, FIXTURE
    _WORKSPACE = tempfile.mkdtemp(prefix="agtmls-install-")
    FIXTURE = mini_registry(Path(_WORKSPACE) / "tree")


def tearDownModule() -> None:
    shutil.rmtree(_WORKSPACE, ignore_errors=True)


class ScriptCase(unittest.TestCase):
    script_name = ""

    @classmethod
    def setUpClass(cls) -> None:
        cls.fixture = FIXTURE
        cls.module = load_script(cls.script_name)
        retarget(cls.module, cls.fixture)

    def setUp(self) -> None:
        self.target = Path(tempfile.mkdtemp(prefix="agtmls-target-")).resolve()
        self.addCleanup(lambda: shutil.rmtree(self.target, ignore_errors=True))

    def drive(self, *args: str) -> tuple[int, str]:
        return run_main(self.module, *args)

    def edit_json(self, relative: str, change) -> None:
        path = self.fixture / relative
        data = json.loads(path.read_text(encoding="utf-8"))
        change(data)
        replace_file(self, path, json.dumps(data, indent=2))


class DoctorRegistryTests(ScriptCase):
    """What the doctor says about the checkout itself."""

    script_name = "agtmls-doctor.py"

    def test_a_healthy_checkout_passes_without_warnings(self) -> None:
        code, output = self.drive("--skip-gate")
        self.assertEqual(code, 0, output)
        self.assertIn("OK: doctor passed with 0 warning(s)", output)
        self.assertIn(f"routing eval coverage is complete: {len(SKILLS)}/{len(SKILLS)}", output)
        self.assertIn("OK   LICENSE-MIT exists", output)
        self.assertIn("OK   plugin skills path exists: ./skills", output)

    def test_a_plain_license_file_is_accepted(self) -> None:
        replace_file(self, self.fixture / "LICENSE", "MIT\n")
        code, output = self.drive("--skip-gate")
        self.assertEqual(code, 0, output)
        self.assertIn("OK   LICENSE exists", output)

    def test_no_license_at_all_is_a_failure(self) -> None:
        replace_file(self, self.fixture / "LICENSE-MIT", None)
        code, output = self.drive("--skip-gate")
        self.assertEqual(code, 1, output)
        self.assertIn("FAIL LICENSE is missing", output)

    def test_a_manifest_missing_a_key_or_a_path_fails(self) -> None:
        def damage(manifest: dict) -> None:
            del manifest["license"]
            manifest["commands"] = ["./commands", "./no-such-commands"]

        self.edit_json(".claude-plugin/plugin.json", damage)
        code, output = self.drive("--skip-gate")
        self.assertEqual(code, 1, output)
        self.assertIn("FAIL plugin manifest missing license", output)
        self.assertIn("OK   plugin commands path exists: ./commands", output)
        self.assertIn("FAIL plugin commands path missing: ./no-such-commands", output)
        self.assertIn("FAIL: 2 failure(s)", output)

    def test_a_manifest_that_declares_no_commands_is_not_asked_about_them(self) -> None:
        """`commands` is optional; its absence must be neither an OK nor a FAIL."""
        self.edit_json(".claude-plugin/plugin.json", lambda manifest: manifest.pop("commands"))
        code, output = self.drive("--skip-gate")
        self.assertEqual(code, 0, output)
        self.assertNotIn("plugin commands path", output)

    def test_a_missing_manifest_fails(self) -> None:
        replace_file(self, self.fixture / ".claude-plugin" / "plugin.json", None)
        code, output = self.drive("--skip-gate")
        self.assertEqual(code, 1, output)
        self.assertIn("FAIL .claude-plugin/plugin.json is missing", output)

    def test_incomplete_eval_coverage_is_a_warning_not_a_failure(self) -> None:
        """A skill with no cases is unmeasured, not broken; the doctor must say which."""
        for cases in ("evals/cases", "evals/behavioral/cases"):
            replace_file(self, self.fixture / cases / "using-agtmls.json", None)
        code, output = self.drive("--skip-gate")
        self.assertEqual(code, 0, output)
        count = len(SKILLS)
        self.assertIn(f"WARN routing eval coverage incomplete: {count - 1}/{count}", output)
        self.assertIn(f"WARN behavioral eval coverage incomplete: {count - 1}/{count}", output)
        self.assertIn("OK: doctor passed with 2 warning(s)", output)

    def test_without_skip_gate_every_check_runs_and_a_failing_one_fails_the_doctor(self) -> None:
        """The doctor re-runs checks.json; a failing check must surface with its output."""
        scripts = self.fixture / "scripts"
        replace_file(self, scripts / "probe_pass.py", "print('fine')\n")
        replace_file(self, scripts / "probe_fail.py", "print('probe says no')\nraise SystemExit(1)\n")
        checks = {"checks": ["probe_pass.py --flag", "", "agtmls-doctor.py --skip-gate", "probe_fail.py"]}
        replace_file(self, self.fixture / "checks.json", json.dumps(checks))
        code, output = self.drive()
        self.assertEqual(code, 1, output)
        self.assertIn("OK   probe_pass.py --flag", output)
        self.assertIn("FAIL probe_fail.py", output)
        self.assertIn("probe says no", output)
        self.assertNotIn("agtmls-doctor.py", output, "the doctor re-ran itself")


class DoctorTargetTests(ScriptCase):
    """What the doctor says about a consumer repository."""

    script_name = "agtmls-doctor.py"

    def install(self, names=SKILLS, prompt: str | None = GENERATED) -> Path:
        skills = self.target / ".claude" / "skills"
        skills.mkdir(parents=True)
        (self.target / ".claude" / "commands").mkdir()
        for name in names:
            (skills / name).symlink_to(self.fixture / "skills" / name)
        if prompt is not None:
            (self.target / "CLAUDE.md").write_text(prompt, encoding="utf-8")
        return skills

    def doctor(self, *extra: str) -> tuple[int, str]:
        return self.drive("--skip-gate", "--target", str(self.target), "--agent", "claude", *extra)

    def test_a_complete_install_is_healthy(self) -> None:
        self.install()
        code, output = self.doctor()
        self.assertEqual(code, 0, output)
        self.assertIn("OK   target .claude/skills exists", output)
        self.assertIn("OK   target .claude/commands exists", output)
        self.assertIn("OK   target expected AgtMLS skill links are present", output)
        self.assertIn("OK   target generated CLAUDE.md exists", output)
        self.assertIn("OK: doctor passed with 0 warning(s)", output)

    def test_a_missing_link_and_a_foreign_prompt_are_named(self) -> None:
        skills = self.install(names=SKILLS[1:], prompt="# My rules\n")
        (skills / SKILLS[0]).mkdir()  # a real directory is not our link
        code, output = self.doctor()
        self.assertEqual(code, 0, output)
        self.assertIn(f"WARN target missing expected AgtMLS skill links: {SKILLS[0]}\n", output)
        self.assertIn("WARN target CLAUDE.md exists but is not AgtMLS-generated", output)

    def test_a_missing_prompt_is_a_warning(self) -> None:
        self.install(prompt=None)
        code, output = self.doctor()
        self.assertEqual(code, 0, "a missing prompt is a warning, not a failure")
        self.assertIn("WARN target generated CLAUDE.md is missing", output)

    def test_skills_only_flags_a_generated_prompt(self) -> None:
        """--skills-only promised no prompt; a generated one means the promise broke."""
        self.install()
        code, output = self.doctor("--skills-only")
        self.assertEqual(code, 0, output)
        self.assertIn("WARN target has generated CLAUDE.md despite --skills-only", output)

    def test_skills_only_accepts_a_hand_written_or_absent_prompt(self) -> None:
        self.install(prompt="# Mine\n")
        code, output = self.doctor("--skills-only")
        self.assertIn("OK   target CLAUDE.md is hand-authored or absent from AgtMLS", output)
        (self.target / "CLAUDE.md").unlink()
        code, output = self.doctor("--skills-only")
        self.assertIn("OK   target has no generated CLAUDE.md", output)
        self.assertEqual(code, 0, output)

    def test_other_agents_are_checked_in_their_own_layout(self) -> None:
        (self.target / ".codex" / "skills").mkdir(parents=True)
        code, output = self.drive("--skip-gate", "--target", str(self.target), "--agent", "codex")
        self.assertEqual(code, 0, output)
        self.assertIn("OK   target .codex/skills exists", output)
        self.assertIn("WARN target .codex/commands is missing", output)
        self.assertIn("WARN target generated AGENTS.md is missing", output)

    def test_every_native_agent_can_be_inspected(self) -> None:
        """`agtmls install ... antigravity` works, so `doctor --agent
        antigravity` has to. The doctor kept its own agent list, and it
        rejected the agent the installer had just installed for."""
        (self.target / ".agents" / "skills").mkdir(parents=True)
        code, output = self.drive("--skip-gate", "--target", str(self.target), "--agent", "antigravity")
        self.assertEqual(code, 0, output)
        self.assertIn("OK   target .agents/skills exists", output)
        self.assertIn("WARN target generated AGENTS.md is missing", output)

    def test_a_link_into_a_sibling_checkout_is_not_ours(self) -> None:
        """`<root>-experiments/skills/x` shares the registry's path prefix. A
        string prefix match counted it as an AgtMLS link; uninstall had the
        same bug and was fixed with is_relative_to."""
        sibling = Path(str(self.fixture) + "-experiments")
        (sibling / "skills" / SKILLS[0]).mkdir(parents=True)
        self.addCleanup(lambda: shutil.rmtree(sibling, ignore_errors=True))
        skills = self.install(names=SKILLS[1:])
        (skills / SKILLS[0]).symlink_to(sibling / "skills" / SKILLS[0])
        code, output = self.doctor()
        self.assertIn(f"WARN target missing expected AgtMLS skill links: {SKILLS[0]}\n", output)

    def test_commands_without_skills_warns_and_checks_no_links(self) -> None:
        (self.target / ".claude" / "commands").mkdir(parents=True)
        (self.target / "CLAUDE.md").write_text(GENERATED, encoding="utf-8")
        code, output = self.doctor()
        self.assertEqual(code, 0, output)
        self.assertIn("WARN target .claude/skills is missing; run setup-workspace.sh", output)
        self.assertNotIn("skill links", output)

    def test_a_target_that_does_not_exist_fails(self) -> None:
        missing = self.target / "gone"
        code, output = self.drive("--skip-gate", "--target", str(missing), "--agent", "claude")
        self.assertEqual(code, 1, output)
        self.assertIn(f"FAIL target repo does not exist: {missing}", output)

    def test_a_target_without_an_agent_is_only_checked_to_exist(self) -> None:
        code, output = self.drive("--skip-gate", "--target", str(self.target))
        self.assertEqual(code, 0, output)
        self.assertIn(f"OK   target repo exists: {self.target}", output)
        self.assertNotIn("skills", output.split("target repo exists", 1)[1])

    def test_a_nested_bundle_directory_is_expanded_when_asked_for(self) -> None:
        """The pre-flat layout kept bundles as skills/<bundle>/<leaf>/."""
        leaf = self.fixture / "skills" / "legacy" / "legacy-leaf"
        leaf.mkdir(parents=True)
        self.addCleanup(lambda: shutil.rmtree(self.fixture / "skills" / "legacy"))
        (leaf / "SKILL.md").write_text("# Legacy\n", encoding="utf-8")
        # Neither a stray file beside the skills nor a leaf without SKILL.md is a skill.
        (self.fixture / "skills" / "legacy" / "assets").mkdir()
        replace_file(self, self.fixture / "skills" / "README.txt", "not a skill\n")
        self.install()
        names = self.module.expected_skill_names(["legacy"])
        self.assertIn("legacy-leaf", names)
        self.assertNotIn("legacy-leaf", self.module.expected_skill_names([]))
        self.assertNotIn("assets", names)
        self.assertNotIn("README.txt", names)
        code, output = self.doctor("--bundle", "legacy")
        self.assertEqual(code, 0, output)
        self.assertIn("WARN target missing expected AgtMLS skill links: legacy-leaf", output)


class ProviderInstallTests(ScriptCase):
    """`agtmls provider-install`: adapter files for agents that are not native."""

    script_name = "provider-install.py"

    def test_an_adapter_lands_without_its_provider_prefix(self) -> None:
        """adapters/openai/AGENTS.md belongs at the target's root, not three levels down."""
        code, output = self.drive("--provider", "openai", "--target", str(self.target), "--profile", "minimal")
        self.assertEqual(code, 0, output)
        adapter = self.target / "AGENTS.md"
        self.assertEqual(output.strip(), str(adapter))
        text = adapter.read_text(encoding="utf-8")
        self.assertTrue(text.startswith("# AgtMLS openai Adapter\n"))
        self.assertIn("Profile: `minimal`", text)
        self.assertIn(f"`{self.fixture}/skills`", text)
        self.assertFalse((self.target / "adapters").exists())

    def test_a_nested_adapter_path_is_created(self) -> None:
        code, output = self.drive("--provider", "cursor", "--target", str(self.target))
        self.assertEqual(code, 0, output)
        self.assertIn("Profile: `all`", (self.target / ".cursor" / "rules" / "agtmls.mdc").read_text(encoding="utf-8"))

    def test_check_passes_only_for_a_current_install(self) -> None:
        args = ("--provider", "openai", "--target", str(self.target))
        code, output = self.drive(*args, "--check")
        self.assertEqual(code, 1, output)
        self.assertIn("FAIL: provider adapter missing or stale", output)
        self.drive(*args)
        code, output = self.drive(*args, "--check")
        self.assertEqual(code, 0, output)
        self.assertIn("OK: provider adapter installed for openai", output)
        (self.target / "AGENTS.md").write_text("edited\n", encoding="utf-8")
        code, output = self.drive(*args, "--check")
        self.assertEqual(code, 1, "--check accepted a stale adapter")

    def test_a_different_profile_makes_the_install_stale(self) -> None:
        self.drive("--provider", "openai", "--target", str(self.target))
        code, _ = self.drive("--provider", "openai", "--target", str(self.target), "--profile", "minimal", "--check")
        self.assertEqual(code, 1)

    def test_an_unknown_provider_writes_nothing(self) -> None:
        code, output = self.drive("--provider", "no-such", "--target", str(self.target))
        self.assertEqual(code, 1)
        self.assertIn("unsupported install provider: no-such", output)
        self.assertEqual(list(self.target.iterdir()), [])

    def test_a_provider_whose_adapter_list_is_malformed_is_unsupported(self) -> None:
        self.edit_json("providers.json", lambda d: d["export_targets"]["openai"].update(adapter_files="AGENTS.md"))
        self.assertNotIn("openai", self.module.load_targets())
        code, _ = self.drive("--provider", "openai", "--target", str(self.target))
        self.assertEqual(code, 1)

    def test_an_unprefixed_adapter_path_is_kept_as_is(self) -> None:
        self.assertEqual(self.module.install_rel("generic", "ADAPTERS.md"), Path("ADAPTERS.md"))
        self.assertEqual(self.module.install_rel("openai", "adapters/other/X.md"), Path("adapters/other/X.md"))


if __name__ == "__main__":
    unittest.main()
