# SPDX-FileCopyrightText: 2026 Sebastien Rousseau
# SPDX-License-Identifier: Apache-2.0 OR MIT
"""Every complaint the whole-tree validators can make, provoked.

These walk the entire repository: Markdown links, JSON syntax, licence
headers, committed secrets and the provenance markers on generated files.
Walking everything makes two things matter that a per-file check never
faces. Each must still name the specific breakage it found, and each must
skip the directories that are not ours -- a scanner that reads
`__pycache__` or `node_modules` fails on content no contributor wrote.

So both directions are tested: a break in the tree is named by its `FAIL:`
line, and the same break inside a skipped directory is not reported at all.
"""

from __future__ import annotations

from .validator_harness import BrokenTreeCase

SPDX_MD = "<!-- SPDX-License-Identifier: Apache-2.0 OR MIT -->\n\n"


class DocLinkBranchTests(BrokenTreeCase):
    """A broken link in shipped docs is a dead end for the reader who follows it."""

    SCRIPT = "validate-doc-links.py"

    def test_a_link_that_leaves_the_repository_is_refused(self) -> None:
        """It may resolve on one machine and nowhere else."""
        self.overwrite("docs/escape.md", SPDX_MD + "# E\n\n[out](../../../outside.md)\n")
        self.assert_fails(
            self.SCRIPT, "FAIL: docs/escape.md: link escapes repo: ../../../outside.md"
        )

    def test_an_angle_bracketed_target_is_resolved_without_its_brackets(self) -> None:
        """CommonMark allows `<...>` around a target; the brackets are not the path.

        The working link must pass and the broken one must still be named, or
        stripping the brackets has either broken resolution or hidden it.
        """
        self.overwrite(
            "docs/angles.md",
            SPDX_MD + "# A\n\n[ok](<../README.md>) and [bad](<../nope.md#part>)\n",
        )
        output = self.assert_fails(
            self.SCRIPT, "FAIL: docs/angles.md: missing local link target: <../nope.md#part>"
        )
        self.assertNotIn("README.md>", output)

    def test_markdown_under_a_skipped_directory_is_not_read(self) -> None:
        self.create_dir("docs/__pycache__")
        self.overwrite("docs/__pycache__/cached.md", "# C\n\n[gone](nowhere.md)\n")
        self.assert_clean(self.SCRIPT)


class JsonFileBranchTests(BrokenTreeCase):
    """Duplicate keys are valid to json.loads, which silently keeps the last."""

    SCRIPT = "validate-json-files.py"

    def test_a_duplicate_key_is_refused(self) -> None:
        self.overwrite("evals/duplicate.json", '{"skill": "a", "skill": "b"}\n')
        self.assert_fails(self.SCRIPT, "FAIL: evals/duplicate.json: duplicate key: skill")

    def test_json_under_a_skipped_directory_is_not_read(self) -> None:
        self.create_dir("evals/__pycache__")
        self.overwrite("evals/__pycache__/cached.json", "{ not json")
        self.assert_clean(self.SCRIPT)


class GeneratedArtifactBranchTests(BrokenTreeCase):
    """Each generated file, and each rule forbidding hand edits, says so in place."""

    SCRIPT = "validate-generated-artifacts.py"

    def strip(self, relative: str, phrase: str) -> None:
        text = (self.fixture / relative).read_text(encoding="utf-8")
        self.assertIn(phrase, text, f"{relative} no longer carries {phrase!r}")
        self.overwrite(relative, text.replace(phrase, ""))

    def test_a_catalog_without_its_generated_marker_is_refused(self) -> None:
        self.strip("CATALOG.md", "Generated by scripts/generate-catalog.py; do not edit by hand.")
        self.assert_fails(self.SCRIPT, "FAIL: CATALOG.md missing generated marker")

    def test_a_schema_without_the_no_manual_edit_rule_is_refused(self) -> None:
        self.strip("references/registry-schema.md", "Do not edit `index.json` manually")
        self.assert_fails(self.SCRIPT, "FAIL: registry schema missing index no-manual-edit rule")

    def test_a_lifecycle_without_the_no_manual_edit_rule_is_refused(self) -> None:
        self.strip("lifecycle.json", "do not edit index.json by hand")
        self.assert_fails(
            self.SCRIPT, "FAIL: lifecycle metadata missing index no-manual-edit rule"
        )


class LicenceHeaderBranchTests(BrokenTreeCase):
    """Only our files need our header; vendored and cached ones are not ours."""

    SCRIPT = "validate-licence-headers.py"

    def test_files_under_skipped_directories_are_not_read(self) -> None:
        """Markdown and code alike: both loops honour the skip list."""
        self.create_dir("node_modules/pkg")
        self.overwrite("node_modules/pkg/README.md", "# Someone else's package\n")
        self.create_dir("scripts/__pycache__")
        self.overwrite("scripts/__pycache__/cached.py", "x = 1\n")
        self.assert_clean(self.SCRIPT)

    def test_the_same_files_outside_a_skipped_directory_are_refused(self) -> None:
        """The control for the test above: these contents do fail when they count."""
        self.overwrite("docs/unheadered.md", "# Ours\n")
        self.overwrite("scripts/unheadered.py", "x = 1\n")
        self.assert_fails(
            self.SCRIPT,
            "FAIL: docs/unheadered.md: missing an SPDX-License-Identifier header",
            "FAIL: scripts/unheadered.py: missing an SPDX-License-Identifier header in its "
            "first 5 lines",
        )


class SecretScanBranchTests(BrokenTreeCase):
    """The scanner reads text files; caches it did not write are not evidence."""

    SCRIPT = "validate-secrets.py"
    # Assembled so this module does not itself trip the scanner it tests.
    TOKEN = "ghp" + "_" + "B" * 24

    def test_a_token_under_a_skipped_directory_is_not_reported(self) -> None:
        self.create_dir("docs/__pycache__")
        self.overwrite("docs/__pycache__/leak.txt", f"{self.TOKEN}\n")
        self.assert_clean(self.SCRIPT)

    def test_the_same_token_elsewhere_is_reported_by_line(self) -> None:
        """The control: the line number is what makes the finding actionable."""
        self.overwrite("docs/leak.txt", f"first line\n{self.TOKEN}\n")
        self.assert_fails(self.SCRIPT, "FAIL: docs/leak.txt:2: likely secret")
