#!/usr/bin/env python3
"""Small command dispatcher for AgtMLS maintenance tasks."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from _lib import lockfile  # noqa: E402  (needs ROOT on the path first)


def run(argv: list[str], cwd: Path = ROOT) -> int:
    return subprocess.call(argv, cwd=cwd)


def agent_paths(agent: str) -> tuple[str, str]:
    if agent == "claude":
        return ".claude", "CLAUDE.md"
    if agent == "aider":
        return ".aider", "CONVENTIONS.md"
    if agent == "codex":
        return ".codex", "AGENTS.md"
    raise ValueError(agent)


def uninstall(target: Path, agent: str, remove_prompt: bool) -> int:
    target = target.resolve()
    dot, prompt = agent_paths(agent)
    removed = 0
    for sub in ["skills", "commands"]:
        directory = target / dot / sub
        if not directory.exists():
            continue
        for entry in directory.iterdir():
            if entry.is_symlink():
                try:
                    resolved = entry.resolve(strict=True)
                except FileNotFoundError:
                    resolved = Path("")
                # A string prefix would also match a sibling checkout whose
                # path merely starts with ours, e.g. ../agtmls-experiments.
                if resolved != Path("") and resolved.is_relative_to(ROOT):
                    entry.unlink()
                    removed += 1
    prompt_path = target / prompt
    if remove_prompt and prompt_path.exists():
        first = prompt_path.read_text(encoding="utf-8", errors="replace").splitlines()[:1]
        if first and "Generated by AgtMLS" in first[0]:
            prompt_path.unlink()
            removed += 1
    print(f"removed {removed} AgtMLS-managed item(s) from {target}")
    return 0


def load_index() -> dict[str, object]:
    return json.loads((ROOT / "index.json").read_text(encoding="utf-8"))


def list_entries(kind: str, bundle: str | None, json_output: bool) -> int:
    index = load_index()
    if kind == "commands":
        entries = index.get("commands", [])
        if json_output:
            print(json.dumps(entries, indent=2, sort_keys=True))
            return 0
        for command in entries:
            print(f"command/{command['name']}  {command['description']}")
        return 0
    skills = index["skills"]
    if bundle:
        skills = [skill for skill in skills if (skill["bundle"] or "_general") == bundle]
    if json_output:
        print(json.dumps(skills, indent=2, sort_keys=True))
        return 0
    for skill in skills:
        prefix = skill["bundle"] or "general"
        print(f"{prefix}/{skill['name']}  {', '.join(skill['tags'])}")
    return 0


def all_entries(index: dict[str, object]) -> list[dict[str, object]]:
    entries: list[dict[str, object]] = []
    for skill in index.get("skills", []):
        item = dict(skill)
        item["entry_type"] = "skill"
        entries.append(item)
    for command in index.get("commands", []):
        item = dict(command)
        item["entry_type"] = "command"
        entries.append(item)
    return entries


def search_entries(query: str, json_output: bool) -> int:
    terms = [term.lower() for term in query.split() if term.strip()]
    entries = []
    for entry in all_entries(load_index()):
        haystack = " ".join(
            str(entry.get(key, ""))
            for key in ["name", "description", "bundle", "path", "tags", "entry_type"]
        ).lower()
        if all(term in haystack for term in terms):
            entries.append(entry)
    if json_output:
        print(json.dumps(entries, indent=2, sort_keys=True))
        return 0
    for entry in entries:
        prefix = entry["entry_type"]
        if entry["entry_type"] == "skill":
            prefix = entry.get("bundle") or "general"
        print(f"{prefix}/{entry['name']}  {entry.get('description', '')}")
    return 0


def show_entry(name: str, json_output: bool) -> int:
    matches = [
        entry for entry in all_entries(load_index())
        if entry.get("name") == name or f"{entry.get('bundle')}/{entry.get('name')}" == name
    ]
    if not matches:
        print(f"no registry entry named {name!r}", file=sys.stderr)
        return 1
    entry = matches[0]
    if json_output:
        print(json.dumps(entry, indent=2, sort_keys=True))
        return 0
    print(f"{entry['entry_type']}: {entry['name']}")
    print(f"path: {entry.get('path', '')}")
    if entry.get("bundle"):
        print(f"bundle: {entry['bundle']}")
    if entry.get("tags"):
        print(f"tags: {', '.join(entry['tags'])}")
    if entry.get("description"):
        print()
        print(entry["description"])
    return 0


def stats(json_output: bool) -> int:
    index = load_index()
    payload = {
        "registry_version": index.get("registry_version"),
        "skills": index.get("skill_count", 0),
        "commands": index.get("command_count", 0),
        "bundles": index.get("bundles", {}),
        "coverage": index.get("coverage", {}),
        "quality": index.get("quality", {}),
    }
    if json_output:
        print(json.dumps(payload, indent=2, sort_keys=True))
        return 0
    print(f"registry: {payload['registry_version']}")
    print(f"skills: {payload['skills']}")
    print(f"commands: {payload['commands']}")
    for name, count in sorted(payload["bundles"].items()):
        label = "general" if name == "_general" else name
        print(f"bundle/{label}: {count}")
    quality = payload.get("quality", {})
    if quality:
        print(f"quality: {quality.get('average_score', 0)}")
    coverage = payload["coverage"]
    for name in sorted(coverage):
        item = coverage[name]
        print(f"{name} coverage: {item.get('covered', 0)}/{item.get('total', 0)}")
    return 0


def profiles(json_output: bool) -> int:
    data = json.loads((ROOT / "profiles.json").read_text(encoding="utf-8"))["profiles"]
    if json_output:
        print(json.dumps(data, indent=2, sort_keys=True))
        return 0
    for name, item in sorted(data.items()):
        bundles = ",".join(item.get("bundles", [])) or "general"
        print(f"{name}  bundles={bundles}  {item.get('description', '')}")
    return 0


def providers(json_output: bool) -> int:
    data = json.loads((ROOT / "providers.json").read_text(encoding="utf-8"))
    if json_output:
        print(json.dumps(data, indent=2, sort_keys=True))
        return 0
    for name in sorted(data.get("native_agents", {})):
        print(f"native/{name}")
    for name in sorted(data.get("export_targets", {})):
        print(f"export/{name}")
    return 0


def verify_registry() -> list[tuple[str, str, str]]:
    """Skills whose on-disk content no longer matches index.json.

    Checked before an install rather than after: copying a tampered skill into
    a consumer repository and then reporting it is not a control.
    """
    from _lib.digest import skill_digest

    drift: list[tuple[str, str, str]] = []
    for skill in load_index().get("skills", []):
        expected = skill.get("integrity")
        if not expected:
            continue
        source = ROOT / skill["path"]
        if not source.is_dir():
            drift.append((skill["name"], expected, "<missing>"))
            continue
        actual = skill_digest(source)
        if actual != expected:
            drift.append((skill["name"], expected, actual))
    return drift


def installed_skill_names(target: Path, agent: str) -> list[str]:
    dot, _ = agent_paths(agent)
    directory = target / dot / "skills"
    if not directory.is_dir():
        return []
    return sorted(entry.name for entry in directory.iterdir() if entry.is_dir() or entry.is_symlink())


def verify_install(target: Path, agent: str, json_output: bool) -> int:
    """Check an installed tree against its lockfile."""
    target = target.resolve()
    dot, _ = agent_paths(agent)
    problems = lockfile.verify(target, target / dot / "skills")

    if json_output:
        print(json.dumps(
            {"target": str(target), "ok": not problems,
             "problems": [{"skill": n, "status": s, "detail": d} for n, s, d in problems]},
            indent=2, sort_keys=True,
        ))
    elif not problems:
        lock = lockfile.read(target) or {}
        print(f"OK: {len(lock.get('skills', []))} skill(s) match the lockfile in {target}")
    else:
        for name, status, detail in problems:
            print(f"{status.upper():<12} {name or '-'}  {detail}", file=sys.stderr)
        print(f"\nFAIL: {len(problems)} integrity problem(s)", file=sys.stderr)

    if not problems:
        return lockfile.EXIT_OK
    # "unmanaged" is informational; only a real mismatch is an integrity failure.
    if all(status == "unmanaged" for _, status, _ in problems):
        return lockfile.EXIT_OK
    return lockfile.EXIT_INTEGRITY_FAILURE


def main() -> int:
    parser = argparse.ArgumentParser(prog="agtmls")
    # dest must not collide with any subparser option dest: `evidence --command`
    # used to overwrite the subcommand name with its own (list) value, which made
    # every dispatch comparison below fail. See CliDispatchTests.
    sub = parser.add_subparsers(dest="subcommand", required=True)

    doctor = sub.add_parser("doctor")
    doctor.add_argument("--target", type=Path)
    doctor.add_argument("--agent", choices=["claude", "aider", "codex"])
    doctor.add_argument("--skills-only", action="store_true")
    doctor.add_argument("--bundle", action="append", default=[])

    status = sub.add_parser("status")
    status.add_argument("--target", type=Path)
    status.add_argument("--agent", choices=["claude", "aider", "codex"])
    status.add_argument("--skills-only", action="store_true")
    status.add_argument("--bundle", action="append", default=[])

    sub.add_parser("check")

    list_cmd = sub.add_parser("list")
    list_cmd.add_argument("kind", nargs="?", choices=["skills", "commands"], default="skills")
    list_cmd.add_argument("--bundle")
    list_cmd.add_argument("--json", action="store_true")

    search = sub.add_parser("search")
    search.add_argument("query")
    search.add_argument("--json", action="store_true")

    show = sub.add_parser("show")
    show.add_argument("name")
    show.add_argument("--json", action="store_true")

    stats_cmd = sub.add_parser("stats")
    stats_cmd.add_argument("--json", action="store_true")

    profiles_cmd = sub.add_parser("profiles")
    profiles_cmd.add_argument("--json", action="store_true")

    providers_cmd = sub.add_parser("providers")
    providers_cmd.add_argument("--json", action="store_true")

    export_cmd = sub.add_parser("export")
    export_cmd.add_argument("--provider", default="generic")
    export_cmd.add_argument("--profile")
    export_cmd.add_argument("--bundle", action="append", default=[])
    export_cmd.add_argument("--out-dir", type=Path)

    docs_site = sub.add_parser("docs-site")
    docs_site.add_argument("--write", action="store_true")
    docs_site.add_argument("--check", action="store_true")

    release_pack = sub.add_parser("release-pack")
    release_pack.add_argument("--out-dir", type=Path)
    release_pack.add_argument("--profile")
    release_pack.add_argument("--provider", action="append", default=[])

    next_version = sub.add_parser("next-version")
    next_version.add_argument("--tag", action="store_true")
    next_version.add_argument("--json", action="store_true")

    bump_version = sub.add_parser("bump-version")
    bump_version.add_argument("--version")
    bump_version.add_argument("--date")
    bump_version.add_argument("--check", action="store_true")

    release_dry_run = sub.add_parser("release-dry-run")
    release_dry_run.add_argument("--version")
    release_dry_run.add_argument("--skip-check", action="store_true")
    release_dry_run.add_argument("--profile")
    release_dry_run.add_argument("--provider", action="append", default=[])

    verify_release_assets = sub.add_parser("verify-release-assets")
    verify_release_assets.add_argument("--tag", default="v0.0.1")
    verify_release_assets.add_argument("--repo")
    verify_release_assets.add_argument("--out-dir", type=Path)

    evolve = sub.add_parser("evolve")
    evolve.add_argument("transcript", type=Path)
    evolve.add_argument("--skill-name", required=True)

    evidence = sub.add_parser("evidence")
    evidence.add_argument("--skill", required=True)
    evidence.add_argument("--command", dest="evidence_commands", action="append", default=[])
    evidence.add_argument("--file", action="append", default=[])
    evidence.add_argument("--outcome", default="recorded")

    agent_card = sub.add_parser("agent-card")
    agent_card.add_argument("--write", action="store_true")
    agent_card.add_argument("--check", action="store_true")

    mcp_resources = sub.add_parser("mcp-resources")
    mcp_resources.add_argument("--write", action="store_true")
    mcp_resources.add_argument("--check", action="store_true")

    plugin_manifests = sub.add_parser("plugin-manifests")
    plugin_manifests.add_argument("--write", action="store_true")
    plugin_manifests.add_argument("--check", action="store_true")

    sbom = sub.add_parser("sbom")
    sbom.add_argument("--write", action="store_true")
    sbom.add_argument("--check", action="store_true")

    provenance = sub.add_parser("provenance")
    provenance.add_argument("--write", action="store_true")
    provenance.add_argument("--check", action="store_true")

    provider_install = sub.add_parser("provider-install")
    provider_install.add_argument("--provider", required=True)
    provider_install.add_argument("--target", type=Path, required=True)
    provider_install.add_argument("--profile")
    provider_install.add_argument("--check", action="store_true")

    sub.add_parser("bench")

    diff_cmd = sub.add_parser("diff")
    diff_cmd.add_argument("--from", dest="old", required=True)
    diff_cmd.add_argument("--to", dest="new", default="index.json")
    diff_cmd.add_argument("--json", action="store_true")

    sub.add_parser("release-check")

    audit_cmd = sub.add_parser("audit", help="statically audit skills for prompt injection, steganography, and security risks")
    audit_cmd.add_argument("path", nargs="?", type=Path, help="path to skill directory or markdown file")
    audit_cmd.add_argument("--all", action="store_true", help="audit all skills in registry")
    audit_cmd.add_argument("--strict", action="store_true", help="fail on warnings")
    audit_cmd.add_argument("--json", action="store_true", help="output JSON")

    import_cmd = sub.add_parser("import-skill")
    import_cmd.add_argument("source", type=Path)
    import_cmd.add_argument("--name")
    import_cmd.add_argument("--bundle")

    index = sub.add_parser("index")
    index.add_argument("--write", action="store_true")
    index.add_argument("--check", action="store_true")

    install = sub.add_parser("install")
    install.add_argument("language")
    install.add_argument("agent", choices=["claude", "aider", "codex"])
    install.add_argument("--target", type=Path, default=Path.cwd())
    install.add_argument("--skills-only", action="store_true")
    install.add_argument(
        "--copy",
        action="store_true",
        help="copy skills instead of symlinking (required when the hub is a packaged wheel)",
    )
    install.add_argument("--bundle", action="append", default=[])
    install.add_argument("--profile")
    install.add_argument(
        "--force",
        action="store_true",
        help="back up and overwrite a prompt file AgtMLS did not generate",
    )
    install.add_argument(
        "--dry-run",
        action="store_true",
        help="print every planned change and exit without touching disk",
    )
    install.add_argument(
        "--no-verify",
        action="store_true",
        help="skip the integrity check against index.json (not recommended)",
    )

    verify = sub.add_parser(
        "verify", help="check an installed tree against its .agtmls/manifest.json lockfile"
    )
    verify.add_argument("agent", choices=["claude", "aider", "codex"])
    verify.add_argument("--target", type=Path, default=Path.cwd())
    verify.add_argument("--json", action="store_true")

    remove = sub.add_parser("uninstall")
    remove.add_argument("agent", choices=["claude", "aider", "codex"])
    remove.add_argument("--target", type=Path, default=Path.cwd())
    remove.add_argument("--remove-prompt", action="store_true")

    propose = sub.add_parser("propose-skill")
    propose.add_argument("transcript", type=Path)
    propose.add_argument("--skill-name", required=True)

    scaffold = sub.add_parser("scaffold-skill")
    scaffold.add_argument("name")
    scaffold.add_argument("--bundle")
    scaffold.add_argument("--title")

    args = parser.parse_args()

    if args.subcommand in {"doctor", "status"}:
        cmd = [sys.executable, str(ROOT / "scripts" / "agtmls-doctor.py")]
        if args.target:
            cmd.extend(["--target", str(args.target)])
        if args.agent:
            cmd.extend(["--agent", args.agent])
        if args.skills_only:
            cmd.append("--skills-only")
        for bundle in args.bundle:
            cmd.extend(["--bundle", bundle])
        return run(cmd)
    if args.subcommand == "check":
        return run([sys.executable, str(ROOT / "scripts" / "run-all-checks.py")])
    if args.subcommand == "list":
        return list_entries(args.kind, args.bundle, args.json)
    if args.subcommand == "search":
        return search_entries(args.query, args.json)
    if args.subcommand == "show":
        return show_entry(args.name, args.json)
    if args.subcommand == "stats":
        return stats(args.json)
    if args.subcommand == "profiles":
        return profiles(args.json)
    if args.subcommand == "providers":
        return providers(args.json)
    if args.subcommand == "export":
        cmd = [sys.executable, str(ROOT / "scripts" / "export-registry.py"), "--provider", args.provider]
        if args.profile:
            cmd.extend(["--profile", args.profile])
        for bundle in args.bundle:
            cmd.extend(["--bundle", bundle])
        if args.out_dir:
            cmd.extend(["--out-dir", str(args.out_dir)])
        return run(cmd)
    if args.subcommand == "docs-site":
        flags = ["--write"] if args.write else ["--check"] if args.check else []
        return run([sys.executable, str(ROOT / "scripts" / "generate-docs-site.py"), *flags])
    if args.subcommand == "release-pack":
        cmd = [sys.executable, str(ROOT / "scripts" / "release-pack.py")]
        if args.out_dir:
            cmd.extend(["--out-dir", str(args.out_dir)])
        if args.profile:
            cmd.extend(["--profile", args.profile])
        for provider in args.provider:
            cmd.extend(["--provider", provider])
        return run(cmd)
    if args.subcommand == "next-version":
        cmd = [sys.executable, str(ROOT / "scripts" / "next-version.py")]
        if args.tag:
            cmd.append("--tag")
        if args.json:
            cmd.append("--json")
        return run(cmd)
    if args.subcommand == "bump-version":
        cmd = [sys.executable, str(ROOT / "scripts" / "bump-version.py")]
        if args.version:
            cmd.extend(["--version", args.version])
        if args.date:
            cmd.extend(["--date", args.date])
        if args.check:
            cmd.append("--check")
        return run(cmd)
    if args.subcommand == "release-dry-run":
        cmd = [sys.executable, str(ROOT / "scripts" / "release-dry-run.py")]
        if args.version:
            cmd.extend(["--version", args.version])
        if args.skip_check:
            cmd.append("--skip-check")
        if args.profile:
            cmd.extend(["--profile", args.profile])
        for provider in args.provider:
            cmd.extend(["--provider", provider])
        return run(cmd)
    if args.subcommand == "verify-release-assets":
        cmd = [sys.executable, str(ROOT / "scripts" / "verify-release-assets.py"), "--tag", args.tag]
        if args.repo:
            cmd.extend(["--repo", args.repo])
        if args.out_dir:
            cmd.extend(["--out-dir", str(args.out_dir)])
        return run(cmd)
    if args.subcommand == "evolve":
        return run([sys.executable, str(ROOT / "scripts" / "evolve-session.py"), str(args.transcript), "--skill-name", args.skill_name])
    if args.subcommand == "evidence":
        cmd = [sys.executable, str(ROOT / "scripts" / "record-evidence.py"), "--skill", args.skill, "--outcome", args.outcome]
        for item in args.evidence_commands:
            cmd.extend(["--command", item])
        for item in args.file:
            cmd.extend(["--file", item])
        return run(cmd)
    if args.subcommand == "agent-card":
        flags = ["--write"] if args.write else ["--check"] if args.check else []
        return run([sys.executable, str(ROOT / "scripts" / "generate-agent-card.py"), *flags])
    if args.subcommand == "mcp-resources":
        flags = ["--write"] if args.write else ["--check"] if args.check else []
        return run([sys.executable, str(ROOT / "scripts" / "generate-mcp-resources.py"), *flags])
    if args.subcommand == "plugin-manifests":
        flags = ["--write"] if args.write else ["--check"] if args.check else []
        return run([sys.executable, str(ROOT / "scripts" / "generate-plugin-manifests.py"), *flags])
    if args.subcommand == "sbom":
        flags = ["--write"] if args.write else ["--check"] if args.check else []
        return run([sys.executable, str(ROOT / "scripts" / "generate-sbom.py"), *flags])
    if args.subcommand == "provenance":
        flags = ["--write"] if args.write else ["--check"] if args.check else []
        return run([sys.executable, str(ROOT / "scripts" / "generate-provenance.py"), *flags])
    if args.subcommand == "provider-install":
        cmd = [sys.executable, str(ROOT / "scripts" / "provider-install.py"), "--provider", args.provider, "--target", str(args.target)]
        if args.profile:
            cmd.extend(["--profile", args.profile])
        if args.check:
            cmd.append("--check")
        return run(cmd)
    if args.subcommand == "bench":
        return run([sys.executable, str(ROOT / "scripts" / "bench.py")])
    if args.subcommand == "diff":
        cmd = [sys.executable, str(ROOT / "scripts" / "registry-diff.py"), "--from", args.old, "--to", args.new]
        if args.json:
            cmd.append("--json")
        return run(cmd)
    if args.subcommand == "release-check":
        return run([sys.executable, str(ROOT / "scripts" / "release-check.py")])
    if args.subcommand == "audit":
        cmd = [sys.executable, str(ROOT / "scripts" / "audit-skill.py")]
        if args.path:
            cmd.append(str(args.path))
        if args.all:
            cmd.append("--all")
        if args.strict:
            cmd.append("--strict")
        if args.json:
            cmd.extend(["--format", "json"])
        return run(cmd)
    if args.subcommand == "import-skill":
        cmd = [sys.executable, str(ROOT / "scripts" / "import-skill.py"), str(args.source)]
        if args.name:
            cmd.extend(["--name", args.name])
        if args.bundle:
            cmd.extend(["--bundle", args.bundle])
        return run(cmd)
    if args.subcommand == "index":
        flags = ["--write"] if args.write else ["--check"] if args.check else []
        return run([sys.executable, str(ROOT / "scripts" / "generate-skill-index.py"), *flags])
    if args.subcommand == "install":
        cmd = [str(ROOT / "scripts" / "setup-workspace.sh"), args.language, args.agent]
        if args.skills_only:
            cmd.append("--skills-only")
        if args.copy:
            cmd.append("--copy")
        if args.force:
            cmd.append("--force")
        if args.dry_run:
            cmd.append("--dry-run")
        bundles = list(args.bundle)
        if args.profile:
            data = json.loads((ROOT / "profiles.json").read_text(encoding="utf-8"))["profiles"]
            profile = data.get(args.profile)
            if profile is None:
                print(f"unknown profile: {args.profile}", file=sys.stderr)
                return 1
            bundles.extend(profile.get("bundles", []))
        for bundle in sorted(set(bundles)):
            cmd.extend(["--bundle", bundle])

        target = args.target.resolve()
        if not args.no_verify and not args.dry_run:
            drift = verify_registry()
            if drift:
                print(
                    f"refusing to install: {len(drift)} skill(s) do not match index.json",
                    file=sys.stderr,
                )
                for name, expected, actual in drift:
                    print(f"  {name}\n    index    {expected}\n    on disk  {actual}", file=sys.stderr)
                print(
                    "\nThe registry has been modified since index.json was generated. Run "
                    "`agtmls index --write` if the change is yours, or re-clone if it is not.",
                    file=sys.stderr,
                )
                return lockfile.EXIT_INTEGRITY_FAILURE

        rc = run(cmd, cwd=target)
        if rc != 0 or args.dry_run:
            return rc

        # Record what landed, so `agtmls verify` has something to check against.
        index = load_index()
        installed = installed_skill_names(target, args.agent)
        payload = lockfile.build(
            target, ROOT, installed,
            "copy" if args.copy else "symlink",
            str(index.get("registry_version", "")),
        )
        path = lockfile.write(target, payload)
        print(f"recorded {len(payload['skills'])} skill(s) in {path.relative_to(target)}")
        return 0
    if args.subcommand == "verify":
        return verify_install(args.target, args.agent, args.json)
    if args.subcommand == "uninstall":
        return uninstall(args.target, args.agent, args.remove_prompt)
    if args.subcommand == "propose-skill":
        return run(
            [
                sys.executable,
                str(ROOT / "scripts" / "propose-skill-from-session.py"),
                str(args.transcript),
                "--skill-name",
                args.skill_name,
            ]
        )
    if args.subcommand == "scaffold-skill":
        cmd = [sys.executable, str(ROOT / "scripts" / "scaffold-skill.py"), args.name]
        if args.bundle:
            cmd.extend(["--bundle", args.bundle])
        if args.title:
            cmd.extend(["--title", args.title])
        return run(cmd)
    return 2


if __name__ == "__main__":
    sys.exit(main())
