#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Sebastien Rousseau
# SPDX-License-Identifier: Apache-2.0 OR MIT
"""Small command dispatcher for AgtMLS maintenance tasks."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from _lib import (  # noqa: E402  (needs ROOT on the path first)
    cli_args,
    lockfile,
    uninstall_steps,
    verify_report,
)
from _lib.cli_parser import build_parser  # noqa: E402  (same path insertion above)


def run(argv: list[str], cwd: Path = ROOT) -> int:
    return subprocess.call(argv, cwd=cwd)


def agent_paths(agent: str) -> tuple[str, str]:
    """The dot-directory and prompt file an agent reads, from providers.json."""
    data = json.loads((ROOT / "providers.json").read_text(encoding="utf-8"))
    item = data["native_agents"].get(agent)
    if item is None:
        raise ValueError(agent)
    return str(Path(item["skills_dir"]).parent), item["prompt_file"]


def skills_dirs(target: Path) -> dict[str, Path]:
    """Each native agent's skills directory in `target`, from providers.json."""
    data = json.loads((ROOT / "providers.json").read_text(encoding="utf-8"))
    return {agent: target / item["skills_dir"] for agent, item in data["native_agents"].items()}


def unregister_aider_prompt(target: Path, prompt: str) -> int:
    """Take the prompt out of .aider.conf.yml's `read:` list, where install
    registered it, so Aider is not left reading a file that is gone. The
    file goes too when nothing else is in it."""
    from _lib import aider_conf

    conf = target / ".aider.conf.yml"
    if not conf.is_file():
        return 0
    text, changed = aider_conf.unregister(conf.read_text(encoding="utf-8"), prompt)
    if not changed:
        return 0
    if text is None:
        conf.unlink()
    else:
        conf.write_text(text, encoding="utf-8")
    return 1


def remove_prompt_file(target: Path, agent: str, prompt: str) -> int:
    """The generated prompt file, only if it still begins with our header."""
    prompt_path = target / prompt
    if not prompt_path.exists():
        return 0
    first = prompt_path.read_text(encoding="utf-8", errors="replace").splitlines()[:1]
    if not (first and "Generated by AgtMLS" in first[0]):
        return 0
    prompt_path.unlink()
    return 1 + (unregister_aider_prompt(target, prompt) if agent == "aider" else 0)


def settle_lockfile(target: Path, lock: dict, agent: str, agent_dirs: dict[str, Path], kept: set[str]) -> int:
    """Forget this agent in the lockfile; delete the file (1) when no agent
    holds anything it records."""
    # One lockfile serves every agent in the target: only this agent's record
    # goes. Deleting the file with one agent's uninstall left the others'
    # skills unrecorded, failing verify and every later uninstall. Once no
    # agent holds anything it records, it goes too, so the next `verify`
    # does not report every skill missing.
    lockfile.forget(lock, agent, agent_dirs, frozenset(kept))
    if lock["skills"]:
        lockfile.write(target, lock)
        return 0
    path = lockfile.lockfile_path(target)
    path.unlink()
    try:
        path.parent.rmdir()
    except OSError:
        pass  # other files live there; not ours
    return 1


def uninstall(target: Path, agent: str, remove_prompt: bool) -> int:
    target = target.resolve()
    dot, prompt = agent_paths(agent)
    base = target / dot
    # Read before anything is removed: an entry from before `agents` was
    # recorded is resolved by which agents hold the skill now.
    lock = lockfile.read(target)
    agent_dirs = skills_dirs(target)
    if lock is not None:
        lockfile.resolve_agents(lock, agent_dirs)
    kept: set[str] = set()
    # The directories something was removed from: once empty, they are
    # removed too, so an uninstall leaves no empty .claude/skills behind.
    # A directory holding anything else is never touched.
    touched: set[str] = set()
    removed = uninstall_steps.remove_registry_links(base, ROOT, touched)

    # A wheel install copies rather than links (the uvx cache is ephemeral),
    # so none of the above is ours there: the previous release removed nothing
    # after `uvx agtmls install`. The lockfile records what was copied. A skill
    # whose digest moved is a local edit, and is left where verify would
    # report it rather than deleted.
    # Copies are this agent's recorded entries, whatever mode the lockfile
    # names: that field is the last install's, and another agent's symlink
    # install used to leave this agent's copies behind.
    if lock is not None:
        removed += uninstall_steps.remove_recorded_copies(lock, agent, base / "skills", kept, touched)
        removed += uninstall_steps.remove_copied_files(base, ROOT, touched)
    if remove_prompt:
        removed += remove_prompt_file(target, agent, prompt)
    if lock is not None:
        removed += settle_lockfile(target, lock, agent, agent_dirs, kept)
    uninstall_steps.prune_empty(base, touched)
    print(f"removed {removed} AgtMLS-managed item(s) from {target}")
    return 0


def load_index() -> dict[str, object]:
    return json.loads((ROOT / "index.json").read_text(encoding="utf-8"))


def print_rows(items: list[dict], json_output: bool, line) -> int:
    """`items` as JSON, or one `line(item)` each."""
    if json_output:
        print(json.dumps(items, indent=2, sort_keys=True))
    else:
        for item in items:
            print(line(item))
    return 0


def list_entries(kind: str, bundle: str | None, json_output: bool) -> int:
    index = load_index()
    if kind == "commands":
        return print_rows(index.get("commands", []), json_output,
                          lambda c: f"command/{c['name']}  {c['description']}")
    skills = [s for s in index["skills"] if not bundle or (s["bundle"] or "_general") == bundle]
    return print_rows(skills, json_output, lambda s: f"{s['bundle'] or 'general'}/{s['name']}  {', '.join(s['tags'])}")


def all_entries(index: dict[str, object]) -> list[dict[str, object]]:
    entries: list[dict[str, object]] = []
    for skill in index.get("skills", []):
        item = dict(skill)
        item["entry_type"] = "skill"
        entries.append(item)
    for command in index.get("commands", []):
        item = dict(command)
        item["entry_type"] = "command"
        entries.append(item)
    return entries


def search_entries(query: str, json_output: bool) -> int:
    terms = [term.lower() for term in query.split() if term.strip()]
    fields = ["name", "description", "bundle", "path", "tags", "entry_type"]
    entries = [
        entry for entry in all_entries(load_index())
        if all(term in " ".join(str(entry.get(key, "")) for key in fields).lower() for term in terms)
    ]

    def line(entry: dict) -> str:
        prefix = (entry.get("bundle") or "general") if entry["entry_type"] == "skill" else entry["entry_type"]
        return f"{prefix}/{entry['name']}  {entry.get('description', '')}"

    return print_rows(entries, json_output, line)


def show_entry(name: str, json_output: bool) -> int:
    matches = [
        entry for entry in all_entries(load_index())
        if entry.get("name") == name or f"{entry.get('bundle')}/{entry.get('name')}" == name
    ]
    if not matches:
        print(f"no registry entry named {name!r}", file=sys.stderr)
        return 1
    entry = matches[0]
    if json_output:
        print(json.dumps(entry, indent=2, sort_keys=True))
        return 0
    print(f"{entry['entry_type']}: {entry['name']}")
    print(f"path: {entry.get('path', '')}")
    if entry.get("bundle"):
        print(f"bundle: {entry['bundle']}")
    if entry.get("tags"):
        print(f"tags: {', '.join(entry['tags'])}")
    if entry.get("description"):
        print()
        print(entry["description"])
    return 0


def stats(json_output: bool) -> int:
    index = load_index()
    payload = {
        "registry_version": index.get("registry_version"),
        "skills": index.get("skill_count", 0),
        "commands": index.get("command_count", 0),
        "bundles": index.get("bundles", {}),
        "coverage": index.get("coverage", {}),
        "quality": index.get("quality", {}),
    }
    if json_output:
        print(json.dumps(payload, indent=2, sort_keys=True))
        return 0
    print(f"registry: {payload['registry_version']}")
    print(f"skills: {payload['skills']}")
    print(f"commands: {payload['commands']}")
    for name, count in sorted(payload["bundles"].items()):
        label = "general" if name == "_general" else name
        print(f"bundle/{label}: {count}")
    quality = payload.get("quality", {})
    if quality:
        print(f"quality: {quality.get('average_score', 0)}")
    coverage = payload["coverage"]
    for name in sorted(coverage):
        item = coverage[name]
        print(f"{name} coverage: {item.get('covered', 0)}/{item.get('total', 0)}")
    return 0


def profiles(json_output: bool) -> int:
    data = json.loads((ROOT / "profiles.json").read_text(encoding="utf-8"))["profiles"]
    if json_output:
        print(json.dumps(data, indent=2, sort_keys=True))
        return 0
    for name, item in sorted(data.items()):
        bundles = ",".join(item.get("bundles", [])) or "general"
        print(f"{name}  bundles={bundles}  {item.get('description', '')}")
    return 0


def providers(json_output: bool) -> int:
    data = json.loads((ROOT / "providers.json").read_text(encoding="utf-8"))
    if json_output:
        print(json.dumps(data, indent=2, sort_keys=True))
        return 0
    for name in sorted(data.get("native_agents", {})):
        print(f"native/{name}")
    for name in sorted(data.get("export_targets", {})):
        print(f"export/{name}")
    return 0


def verify_registry() -> list[tuple[str, str, str]]:
    """Skills whose on-disk content no longer matches index.json.

    Checked before an install rather than after: copying a tampered skill into
    a consumer repository and then reporting it is not a control.
    """
    from _lib.digest import skill_digest

    drift: list[tuple[str, str, str]] = []
    for skill in load_index().get("skills", []):
        expected = skill.get("integrity")
        if not expected:
            # Skipping this let anyone who could edit index.json exempt a
            # skill from the check by deleting its digest. Fail closed.
            drift.append((skill["name"], "<no digest>", "<unverifiable>"))
            continue
        source = ROOT / skill["path"]
        if not source.is_dir():
            drift.append((skill["name"], expected, "<missing>"))
            continue
        actual = skill_digest(source)
        if actual != expected:
            drift.append((skill["name"], expected, actual))
    return drift


def installed_skill_names(target: Path, agent: str) -> list[str]:
    dot, _ = agent_paths(agent)
    directory = target / dot / "skills"
    if not directory.is_dir():
        return []
    return sorted(entry.name for entry in directory.iterdir() if entry.is_dir() or entry.is_symlink())


def live_check(target: Path, agent: str) -> dict:
    """Ask the agent which skills it loads in `target` (verify --live).

    The lockfile proves the bytes; only the agent can say it reads them. A
    skill on disk that the agent does not list is reported, since it will
    never be used. Returns {"loaded": n, "missing": [...]} or {"error": ...}.
    """
    from _lib import context_cost, liveness

    item = json.loads((ROOT / "providers.json").read_text(encoding="utf-8"))["native_agents"][agent]
    lock = lockfile.read(target) or {}
    expected = sorted(entry["name"] for entry in lockfile.entries_for(lock, agent))
    try:
        listed = liveness.listed_skills(item, target)
    except liveness.ProbeError as exc:
        return {"error": str(exc)}
    # A description the agent shortens past its listing budget still loads,
    # but routes worse; it is named, and does not fail the check.
    shown = {name: listed[name] for name in expected if name in listed}
    cut = context_cost.shortened(target / agent_paths(agent)[0] / "skills", shown)
    return {"loaded": len(shown), "expected": len(expected),
            "missing": [name for name in expected if name not in listed],
            "shortened": [list(entry) for entry in cut]}


def verify_install(target: Path, agent: str, json_output: bool, require_signed: bool = False,
                   live: bool = False) -> int:
    """Check an installed tree against its lockfile, the index signature and
    the advisory feed (agtmls-spec 6, 9 and 11).

    Exit precedence (11.4): 5, then 3, then 6, then 4. Nothing can be
    concluded from a source that does not verify, so a bad signature
    outranks the revocation an unverifiable feed claims.
    """
    from _lib import signatures

    target = target.resolve()
    dot, _ = agent_paths(agent)
    problems = lockfile.verify(target, target / dot / "skills", agent)
    try:
        statuses = verify_report.trust_statuses(ROOT, require_signed)
    except signatures.ToolMissing as exc:
        print(f"error: {exc}", file=sys.stderr)
        return lockfile.EXIT_ERROR
    hits, notes = verify_report.revocations(ROOT, target, statuses[1])
    integrity = [p for p in problems if p[1] != "unmanaged"]
    code = verify_report.verify_code(statuses, integrity, hits, require_signed)

    live_result = live_check(target, agent) if live else None
    code = verify_report.with_live(code, live_result)

    if json_output:
        verify_report.print_verify_json(target, code, problems, statuses, hits, notes, live_result)
    else:
        verify_report.print_verify_text(target, agent, code, problems, statuses, hits, notes, live_result)
    return code


# --- dispatch -------------------------------------------------------------
# One small handler per subcommand, looked up in HANDLERS. Each builds the
# command line of the script it forwards to, or answers in-process. They call
# run() and the other handlers by name at call time, so a test that stubs one
# sees every subcommand go through the stub.


def script(name: str, *argv: str) -> list[str]:
    """`python3 scripts/<name> argv...`."""
    return [sys.executable, str(ROOT / "scripts" / name), *argv]


def write_or_check(name: str):
    """A generator subcommand: `--write`, `--check`, or neither."""
    def handler(args) -> int:
        flags = ["--write"] if args.write else ["--check"] if args.check else []
        return run(script(name, *flags))
    return handler


def doctor_command(args) -> int:
    cmd = script("agtmls-doctor.py")
    # The doctor runs with the registry as its working directory, so a
    # relative target must be resolved here, against the caller's:
    # `doctor --target .` from a wheel inspected the registry itself.
    cli_args.option(cmd, "--target", args.target and args.target.resolve())
    cli_args.option(cmd, "--agent", args.agent)
    cli_args.switch(cmd, "--skills-only", args.skills_only)
    cli_args.switch(cmd, "--installed", args.installed)
    cli_args.repeated(cmd, "--bundle", args.bundle)
    return run(cmd)


def export_command(args) -> int:
    cmd = script("export-registry.py", "--provider", args.provider)
    cli_args.option(cmd, "--profile", args.profile)
    cli_args.repeated(cmd, "--bundle", args.bundle)
    cli_args.option(cmd, "--out-dir", args.out_dir)
    return run(cmd)


def release_pack_command(args) -> int:
    cmd = script("release-pack.py")
    cli_args.option(cmd, "--out-dir", args.out_dir)
    cli_args.option(cmd, "--profile", args.profile)
    cli_args.repeated(cmd, "--provider", args.provider)
    return run(cmd)


def next_version_command(args) -> int:
    cmd = script("next-version.py")
    cli_args.switch(cmd, "--tag", args.tag)
    cli_args.switch(cmd, "--json", args.json)
    return run(cmd)


def bump_version_command(args) -> int:
    cmd = script("bump-version.py")
    cli_args.option(cmd, "--version", args.version)
    cli_args.option(cmd, "--date", args.date)
    cli_args.switch(cmd, "--check", args.check)
    return run(cmd)


def release_dry_run_command(args) -> int:
    cmd = script("release-dry-run.py")
    cli_args.option(cmd, "--version", args.version)
    cli_args.switch(cmd, "--skip-check", args.skip_check)
    cli_args.option(cmd, "--profile", args.profile)
    cli_args.repeated(cmd, "--provider", args.provider)
    return run(cmd)


def verify_release_assets_command(args) -> int:
    cmd = script("verify-release-assets.py", "--tag", args.tag)
    cli_args.option(cmd, "--repo", args.repo)
    cli_args.option(cmd, "--out-dir", args.out_dir)
    return run(cmd)


def evidence_command(args) -> int:
    cmd = script("record-evidence.py", "--skill", args.skill, "--outcome", args.outcome)
    cli_args.repeated(cmd, "--command", args.evidence_commands)
    cli_args.repeated(cmd, "--file", args.file)
    return run(cmd)


def provider_install_command(args) -> int:
    cmd = script("provider-install.py", "--provider", args.provider, "--target", str(args.target))
    cli_args.option(cmd, "--profile", args.profile)
    cli_args.switch(cmd, "--check", args.check)
    return run(cmd)


def diff_command(args) -> int:
    # registry-diff runs from the checkout, so a relative path the caller
    # typed would be looked up there. Revision specs pass through as-is.
    cmd = script("registry-diff.py", "--from", cli_args.callers_path(args.old))
    cli_args.option(cmd, "--to", args.new and cli_args.callers_path(args.new))
    cli_args.switch(cmd, "--json", args.json)
    return run(cmd)


def audit_command(args) -> int:
    cmd = script("audit-skill.py")
    if args.path:
        cmd.append(str(args.path))
    cli_args.switch(cmd, "--all", args.all)
    cli_args.option(cmd, "--foreign", args.foreign and cli_args.foreign_target(args.foreign))
    cli_args.switch(cmd, "--strict", args.strict)
    cli_args.switch(cmd, "--pedantic", args.pedantic)
    cli_args.option(cmd, "--format", (args.format or args.json) and (args.format or "json"))
    cli_args.option(cmd, "--baseline", args.baseline and args.baseline.resolve())
    cli_args.option(cmd, "--write-baseline", args.write_baseline and args.write_baseline.resolve())
    return run(cmd)


def import_skill_command(args) -> int:
    cmd = script("import-skill.py", str(args.source))
    cli_args.option(cmd, "--name", args.name)
    cli_args.option(cmd, "--bundle", args.bundle)
    return run(cmd)


def install_bundles(args) -> list[str] | None:
    """The bundles to install: the named ones plus a profile's, or None for
    an unknown profile."""
    bundles = list(args.bundle)
    if args.profile:
        profile = json.loads((ROOT / "profiles.json").read_text(encoding="utf-8"))["profiles"].get(args.profile)
        if profile is None:
            print(f"unknown profile: {args.profile}", file=sys.stderr)
            return None
        bundles.extend(profile.get("bundles", []))
    return sorted(set(bundles))


def refuse_drift() -> int | None:
    """Exit 3 before copying anything when the registry no longer matches
    index.json; None when it does."""
    drift = verify_registry()
    if not drift:
        return None
    print(f"refusing to install: {len(drift)} skill(s) do not match index.json", file=sys.stderr)
    for name, expected, actual in drift:
        print(f"  {name}\n    index    {expected}\n    on disk  {actual}", file=sys.stderr)
    print(
        "\nThe registry has been modified since index.json was generated. Run "
        "`agtmls index --write` if the change is yours, or re-clone if it is not.",
        file=sys.stderr,
    )
    return lockfile.EXIT_INTEGRITY_FAILURE


def record_install(args, target: Path) -> int:
    """Record what landed, so `agtmls verify` has something to check against."""
    installed = installed_skill_names(target, args.agent)
    payload = lockfile.record(
        target, ROOT, installed,
        "copy" if args.copy else "symlink",
        str(load_index().get("registry_version", "")),
        args.agent, skills_dirs(target),
    )
    path = lockfile.write(target, payload)
    print(f"recorded {len(lockfile.entries_for(payload, args.agent))} skill(s) in {path.relative_to(target)}")
    return 0


def install_command(args) -> int:
    cmd = [str(ROOT / "scripts" / "setup-workspace.sh"), args.language, args.agent]
    for flag, on in (("--skills-only", args.skills_only), ("--copy", args.copy),
                     ("--force", args.force), ("--dry-run", args.dry_run)):
        cli_args.switch(cmd, flag, on)
    bundles = install_bundles(args)
    if bundles is None:
        return 1
    cli_args.repeated(cmd, "--bundle", bundles)
    target = args.target.resolve()
    refused = None if args.no_verify or args.dry_run else refuse_drift()
    if refused is not None:
        return refused
    rc = run(cmd, cwd=target)
    if rc != 0 or args.dry_run:
        return rc
    return record_install(args, target)


def scaffold_skill_command(args) -> int:
    cmd = script("scaffold-skill.py", args.name)
    cli_args.option(cmd, "--bundle", args.bundle)
    cli_args.option(cmd, "--title", args.title)
    return run(cmd)


HANDLERS = {
    "doctor": doctor_command,
    "status": doctor_command,
    "check": lambda args: run(script("run-all-checks.py")),
    "list": lambda args: list_entries(args.kind, args.bundle, args.json),
    "search": lambda args: search_entries(args.query, args.json),
    "show": lambda args: show_entry(args.name, args.json),
    "stats": lambda args: stats(args.json),
    "profiles": lambda args: profiles(args.json),
    "providers": lambda args: providers(args.json),
    "export": export_command,
    "docs-site": write_or_check("generate-docs-site.py"),
    "release-pack": release_pack_command,
    "next-version": next_version_command,
    "bump-version": bump_version_command,
    "release-dry-run": release_dry_run_command,
    "verify-release-assets": verify_release_assets_command,
    "evolve": lambda args: run(script("evolve-session.py", str(args.transcript), "--skill-name", args.skill_name)),
    "evidence": evidence_command,
    "mcp-resources": write_or_check("generate-mcp-resources.py"),
    "plugin-manifests": write_or_check("generate-plugin-manifests.py"),
    "sbom": write_or_check("generate-sbom.py"),
    "provenance": write_or_check("generate-provenance.py"),
    "provider-install": provider_install_command,
    "bench": lambda args: run(script("bench.py")),
    "diff": diff_command,
    "release-check": lambda args: run(script("release-check.py")),
    "audit": audit_command,
    "import-skill": import_skill_command,
    "index": write_or_check("generate-skill-index.py"),
    "install": install_command,
    "verify": lambda args: verify_install(args.target, args.agent, args.json, args.signatures, args.live),
    "uninstall": lambda args: uninstall(args.target, args.agent, args.remove_prompt),
    "propose-skill": lambda args: run(script("propose-skill-from-session.py", str(args.transcript), "--skill-name", args.skill_name)),
    "scaffold-skill": scaffold_skill_command,
}


def main() -> int:
    args = build_parser().parse_args()
    handler = HANDLERS.get(args.subcommand)
    return handler(args) if handler else 2


if __name__ == "__main__":
    sys.exit(main())
