#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Sebastien Rousseau
# SPDX-License-Identifier: Apache-2.0 OR MIT
"""Small command dispatcher for AgtMLS maintenance tasks."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from _lib import lockfile  # noqa: E402  (needs ROOT on the path first)
from _lib.cli_parser import build_parser  # noqa: E402  (same path insertion above)


def run(argv: list[str], cwd: Path = ROOT) -> int:
    return subprocess.call(argv, cwd=cwd)


def agent_paths(agent: str) -> tuple[str, str]:
    """The dot-directory and prompt file an agent reads, from providers.json."""
    data = json.loads((ROOT / "providers.json").read_text(encoding="utf-8"))
    item = data["native_agents"].get(agent)
    if item is None:
        raise ValueError(agent)
    return str(Path(item["skills_dir"]).parent), item["prompt_file"]


def uninstall(target: Path, agent: str, remove_prompt: bool) -> int:
    target = target.resolve()
    dot, prompt = agent_paths(agent)
    removed = 0
    for sub in ["skills", "commands", "agents"]:
        directory = target / dot / sub
        if not directory.exists():
            continue
        for entry in directory.iterdir():
            if entry.is_symlink():
                try:
                    resolved = entry.resolve(strict=True)
                except FileNotFoundError:
                    resolved = Path("")
                # A string prefix would also match a sibling checkout whose
                # path merely starts with ours, e.g. ../agtmls-experiments.
                if resolved != Path("") and resolved.is_relative_to(ROOT):
                    entry.unlink()
                    removed += 1

    # A wheel install copies rather than links (the uvx cache is ephemeral),
    # so none of the above is ours there: the previous release removed nothing
    # after `uvx agtmls install`. The lockfile records what was copied. A skill
    # whose digest moved is a local edit, and is left where verify would
    # report it rather than deleted.
    lock = lockfile.read(target)
    skills_dir = target / dot / "skills"
    if lock is not None and lock.get("mode") == "copy":
        from _lib.digest import skill_digest

        for entry in lock.get("skills", []):
            installed = skills_dir / entry.get("path", entry["name"])
            if installed.is_symlink() or not installed.is_dir():
                continue
            if skill_digest(installed) != entry["integrity"]:
                print(f"   {entry['name']}: modified since install; left in place")
                continue
            shutil.rmtree(installed)
            removed += 1
        for sub in ["commands", "agents"]:
            directory = target / dot / sub
            if not directory.is_dir():
                continue
            for entry in sorted(directory.iterdir()):
                source = ROOT / sub / entry.name
                if (entry.is_file() and not entry.is_symlink() and source.is_file()
                        and entry.read_bytes() == source.read_bytes()):
                    entry.unlink()
                    removed += 1

    prompt_path = target / prompt
    if remove_prompt and prompt_path.exists():
        first = prompt_path.read_text(encoding="utf-8", errors="replace").splitlines()[:1]
        if first and "Generated by AgtMLS" in first[0]:
            prompt_path.unlink()
            removed += 1

    # A lockfile describing nothing that is still installed would make the
    # next `verify` report every skill missing.
    if lock is not None and not any(
        (skills_dir / entry.get("path", entry["name"])).exists() for entry in lock.get("skills", [])
    ):
        path = lockfile.lockfile_path(target)
        path.unlink()
        removed += 1
        try:
            path.parent.rmdir()
        except OSError:
            pass  # other files live there; not ours
    print(f"removed {removed} AgtMLS-managed item(s) from {target}")
    return 0


def load_index() -> dict[str, object]:
    return json.loads((ROOT / "index.json").read_text(encoding="utf-8"))


def list_entries(kind: str, bundle: str | None, json_output: bool) -> int:
    index = load_index()
    if kind == "commands":
        entries = index.get("commands", [])
        if json_output:
            print(json.dumps(entries, indent=2, sort_keys=True))
            return 0
        for command in entries:
            print(f"command/{command['name']}  {command['description']}")
        return 0
    skills = index["skills"]
    if bundle:
        skills = [skill for skill in skills if (skill["bundle"] or "_general") == bundle]
    if json_output:
        print(json.dumps(skills, indent=2, sort_keys=True))
        return 0
    for skill in skills:
        prefix = skill["bundle"] or "general"
        print(f"{prefix}/{skill['name']}  {', '.join(skill['tags'])}")
    return 0


def all_entries(index: dict[str, object]) -> list[dict[str, object]]:
    entries: list[dict[str, object]] = []
    for skill in index.get("skills", []):
        item = dict(skill)
        item["entry_type"] = "skill"
        entries.append(item)
    for command in index.get("commands", []):
        item = dict(command)
        item["entry_type"] = "command"
        entries.append(item)
    return entries


def search_entries(query: str, json_output: bool) -> int:
    terms = [term.lower() for term in query.split() if term.strip()]
    entries = []
    for entry in all_entries(load_index()):
        haystack = " ".join(
            str(entry.get(key, ""))
            for key in ["name", "description", "bundle", "path", "tags", "entry_type"]
        ).lower()
        if all(term in haystack for term in terms):
            entries.append(entry)
    if json_output:
        print(json.dumps(entries, indent=2, sort_keys=True))
        return 0
    for entry in entries:
        prefix = entry["entry_type"]
        if entry["entry_type"] == "skill":
            prefix = entry.get("bundle") or "general"
        print(f"{prefix}/{entry['name']}  {entry.get('description', '')}")
    return 0


def show_entry(name: str, json_output: bool) -> int:
    matches = [
        entry for entry in all_entries(load_index())
        if entry.get("name") == name or f"{entry.get('bundle')}/{entry.get('name')}" == name
    ]
    if not matches:
        print(f"no registry entry named {name!r}", file=sys.stderr)
        return 1
    entry = matches[0]
    if json_output:
        print(json.dumps(entry, indent=2, sort_keys=True))
        return 0
    print(f"{entry['entry_type']}: {entry['name']}")
    print(f"path: {entry.get('path', '')}")
    if entry.get("bundle"):
        print(f"bundle: {entry['bundle']}")
    if entry.get("tags"):
        print(f"tags: {', '.join(entry['tags'])}")
    if entry.get("description"):
        print()
        print(entry["description"])
    return 0


def stats(json_output: bool) -> int:
    index = load_index()
    payload = {
        "registry_version": index.get("registry_version"),
        "skills": index.get("skill_count", 0),
        "commands": index.get("command_count", 0),
        "bundles": index.get("bundles", {}),
        "coverage": index.get("coverage", {}),
        "quality": index.get("quality", {}),
    }
    if json_output:
        print(json.dumps(payload, indent=2, sort_keys=True))
        return 0
    print(f"registry: {payload['registry_version']}")
    print(f"skills: {payload['skills']}")
    print(f"commands: {payload['commands']}")
    for name, count in sorted(payload["bundles"].items()):
        label = "general" if name == "_general" else name
        print(f"bundle/{label}: {count}")
    quality = payload.get("quality", {})
    if quality:
        print(f"quality: {quality.get('average_score', 0)}")
    coverage = payload["coverage"]
    for name in sorted(coverage):
        item = coverage[name]
        print(f"{name} coverage: {item.get('covered', 0)}/{item.get('total', 0)}")
    return 0


def profiles(json_output: bool) -> int:
    data = json.loads((ROOT / "profiles.json").read_text(encoding="utf-8"))["profiles"]
    if json_output:
        print(json.dumps(data, indent=2, sort_keys=True))
        return 0
    for name, item in sorted(data.items()):
        bundles = ",".join(item.get("bundles", [])) or "general"
        print(f"{name}  bundles={bundles}  {item.get('description', '')}")
    return 0


def providers(json_output: bool) -> int:
    data = json.loads((ROOT / "providers.json").read_text(encoding="utf-8"))
    if json_output:
        print(json.dumps(data, indent=2, sort_keys=True))
        return 0
    for name in sorted(data.get("native_agents", {})):
        print(f"native/{name}")
    for name in sorted(data.get("export_targets", {})):
        print(f"export/{name}")
    return 0


def verify_registry() -> list[tuple[str, str, str]]:
    """Skills whose on-disk content no longer matches index.json.

    Checked before an install rather than after: copying a tampered skill into
    a consumer repository and then reporting it is not a control.
    """
    from _lib.digest import skill_digest

    drift: list[tuple[str, str, str]] = []
    for skill in load_index().get("skills", []):
        expected = skill.get("integrity")
        if not expected:
            # Skipping this let anyone who could edit index.json exempt a
            # skill from the check by deleting its digest. Fail closed.
            drift.append((skill["name"], "<no digest>", "<unverifiable>"))
            continue
        source = ROOT / skill["path"]
        if not source.is_dir():
            drift.append((skill["name"], expected, "<missing>"))
            continue
        actual = skill_digest(source)
        if actual != expected:
            drift.append((skill["name"], expected, actual))
    return drift


def installed_skill_names(target: Path, agent: str) -> list[str]:
    dot, _ = agent_paths(agent)
    directory = target / dot / "skills"
    if not directory.is_dir():
        return []
    return sorted(entry.name for entry in directory.iterdir() if entry.is_dir() or entry.is_symlink())


def verify_install(target: Path, agent: str, json_output: bool) -> int:
    """Check an installed tree against its lockfile."""
    target = target.resolve()
    dot, _ = agent_paths(agent)
    problems = lockfile.verify(target, target / dot / "skills")

    if json_output:
        print(json.dumps(
            {"target": str(target), "ok": not problems,
             "problems": [{"skill": n, "status": s, "detail": d} for n, s, d in problems]},
            indent=2, sort_keys=True,
        ))
    elif not problems:
        lock = lockfile.read(target) or {}
        print(f"OK: {len(lock.get('skills', []))} skill(s) match the lockfile in {target}")
    else:
        for name, status, detail in problems:
            print(f"{status.upper():<12} {name or '-'}  {detail}", file=sys.stderr)
        print(f"\nFAIL: {len(problems)} integrity problem(s)", file=sys.stderr)

    if not problems:
        return lockfile.EXIT_OK
    # "unmanaged" is informational; only a real mismatch is an integrity failure.
    if all(status == "unmanaged" for _, status, _ in problems):
        return lockfile.EXIT_OK
    return lockfile.EXIT_INTEGRITY_FAILURE


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    if args.subcommand in {"doctor", "status"}:
        cmd = [sys.executable, str(ROOT / "scripts" / "agtmls-doctor.py")]
        if args.target:
            # The doctor runs with the registry as its working directory, so
            # a relative target must be resolved here, against the caller's:
            # `doctor --target .` from a wheel inspected the registry itself.
            cmd.extend(["--target", str(args.target.resolve())])
        if args.agent:
            cmd.extend(["--agent", args.agent])
        if args.skills_only:
            cmd.append("--skills-only")
        if args.installed:
            cmd.append("--installed")
        for bundle in args.bundle:
            cmd.extend(["--bundle", bundle])
        return run(cmd)
    if args.subcommand == "check":
        return run([sys.executable, str(ROOT / "scripts" / "run-all-checks.py")])
    if args.subcommand == "list":
        return list_entries(args.kind, args.bundle, args.json)
    if args.subcommand == "search":
        return search_entries(args.query, args.json)
    if args.subcommand == "show":
        return show_entry(args.name, args.json)
    if args.subcommand == "stats":
        return stats(args.json)
    if args.subcommand == "profiles":
        return profiles(args.json)
    if args.subcommand == "providers":
        return providers(args.json)
    if args.subcommand == "export":
        cmd = [sys.executable, str(ROOT / "scripts" / "export-registry.py"), "--provider", args.provider]
        if args.profile:
            cmd.extend(["--profile", args.profile])
        for bundle in args.bundle:
            cmd.extend(["--bundle", bundle])
        if args.out_dir:
            cmd.extend(["--out-dir", str(args.out_dir)])
        return run(cmd)
    if args.subcommand == "docs-site":
        flags = ["--write"] if args.write else ["--check"] if args.check else []
        return run([sys.executable, str(ROOT / "scripts" / "generate-docs-site.py"), *flags])
    if args.subcommand == "release-pack":
        cmd = [sys.executable, str(ROOT / "scripts" / "release-pack.py")]
        if args.out_dir:
            cmd.extend(["--out-dir", str(args.out_dir)])
        if args.profile:
            cmd.extend(["--profile", args.profile])
        for provider in args.provider:
            cmd.extend(["--provider", provider])
        return run(cmd)
    if args.subcommand == "next-version":
        cmd = [sys.executable, str(ROOT / "scripts" / "next-version.py")]
        if args.tag:
            cmd.append("--tag")
        if args.json:
            cmd.append("--json")
        return run(cmd)
    if args.subcommand == "bump-version":
        cmd = [sys.executable, str(ROOT / "scripts" / "bump-version.py")]
        if args.version:
            cmd.extend(["--version", args.version])
        if args.date:
            cmd.extend(["--date", args.date])
        if args.check:
            cmd.append("--check")
        return run(cmd)
    if args.subcommand == "release-dry-run":
        cmd = [sys.executable, str(ROOT / "scripts" / "release-dry-run.py")]
        if args.version:
            cmd.extend(["--version", args.version])
        if args.skip_check:
            cmd.append("--skip-check")
        if args.profile:
            cmd.extend(["--profile", args.profile])
        for provider in args.provider:
            cmd.extend(["--provider", provider])
        return run(cmd)
    if args.subcommand == "verify-release-assets":
        cmd = [sys.executable, str(ROOT / "scripts" / "verify-release-assets.py"), "--tag", args.tag]
        if args.repo:
            cmd.extend(["--repo", args.repo])
        if args.out_dir:
            cmd.extend(["--out-dir", str(args.out_dir)])
        return run(cmd)
    if args.subcommand == "evolve":
        return run([sys.executable, str(ROOT / "scripts" / "evolve-session.py"), str(args.transcript), "--skill-name", args.skill_name])
    if args.subcommand == "evidence":
        cmd = [sys.executable, str(ROOT / "scripts" / "record-evidence.py"), "--skill", args.skill, "--outcome", args.outcome]
        for item in args.evidence_commands:
            cmd.extend(["--command", item])
        for item in args.file:
            cmd.extend(["--file", item])
        return run(cmd)
    if args.subcommand == "mcp-resources":
        flags = ["--write"] if args.write else ["--check"] if args.check else []
        return run([sys.executable, str(ROOT / "scripts" / "generate-mcp-resources.py"), *flags])
    if args.subcommand == "plugin-manifests":
        flags = ["--write"] if args.write else ["--check"] if args.check else []
        return run([sys.executable, str(ROOT / "scripts" / "generate-plugin-manifests.py"), *flags])
    if args.subcommand == "sbom":
        flags = ["--write"] if args.write else ["--check"] if args.check else []
        return run([sys.executable, str(ROOT / "scripts" / "generate-sbom.py"), *flags])
    if args.subcommand == "provenance":
        flags = ["--write"] if args.write else ["--check"] if args.check else []
        return run([sys.executable, str(ROOT / "scripts" / "generate-provenance.py"), *flags])
    if args.subcommand == "provider-install":
        cmd = [sys.executable, str(ROOT / "scripts" / "provider-install.py"), "--provider", args.provider, "--target", str(args.target)]
        if args.profile:
            cmd.extend(["--profile", args.profile])
        if args.check:
            cmd.append("--check")
        return run(cmd)
    if args.subcommand == "bench":
        return run([sys.executable, str(ROOT / "scripts" / "bench.py")])
    if args.subcommand == "diff":
        # registry-diff runs from the checkout, so a relative path the caller
        # typed would be looked up there. Revision specs pass through as-is.
        def callers(spec: str) -> str:
            return str(Path(spec).resolve()) if Path(spec).exists() else spec

        cmd = [sys.executable, str(ROOT / "scripts" / "registry-diff.py"), "--from", callers(args.old)]
        if args.new:
            cmd.extend(["--to", callers(args.new)])
        if args.json:
            cmd.append("--json")
        return run(cmd)
    if args.subcommand == "release-check":
        return run([sys.executable, str(ROOT / "scripts" / "release-check.py")])
    if args.subcommand == "audit":
        cmd = [sys.executable, str(ROOT / "scripts" / "audit-skill.py")]
        if args.path:
            cmd.append(str(args.path))
        if args.all:
            cmd.append("--all")
        if args.strict:
            cmd.append("--strict")
        if args.format or args.json:
            cmd.extend(["--format", args.format or "json"])
        if args.baseline:
            cmd.extend(["--baseline", str(args.baseline.resolve())])
        if args.write_baseline:
            cmd.extend(["--write-baseline", str(args.write_baseline.resolve())])
        return run(cmd)
    if args.subcommand == "import-skill":
        cmd = [sys.executable, str(ROOT / "scripts" / "import-skill.py"), str(args.source)]
        if args.name:
            cmd.extend(["--name", args.name])
        if args.bundle:
            cmd.extend(["--bundle", args.bundle])
        return run(cmd)
    if args.subcommand == "index":
        flags = ["--write"] if args.write else ["--check"] if args.check else []
        return run([sys.executable, str(ROOT / "scripts" / "generate-skill-index.py"), *flags])
    if args.subcommand == "install":
        cmd = [str(ROOT / "scripts" / "setup-workspace.sh"), args.language, args.agent]
        if args.skills_only:
            cmd.append("--skills-only")
        if args.copy:
            cmd.append("--copy")
        if args.force:
            cmd.append("--force")
        if args.dry_run:
            cmd.append("--dry-run")
        bundles = list(args.bundle)
        if args.profile:
            data = json.loads((ROOT / "profiles.json").read_text(encoding="utf-8"))["profiles"]
            profile = data.get(args.profile)
            if profile is None:
                print(f"unknown profile: {args.profile}", file=sys.stderr)
                return 1
            bundles.extend(profile.get("bundles", []))
        for bundle in sorted(set(bundles)):
            cmd.extend(["--bundle", bundle])

        target = args.target.resolve()
        if not args.no_verify and not args.dry_run:
            drift = verify_registry()
            if drift:
                print(
                    f"refusing to install: {len(drift)} skill(s) do not match index.json",
                    file=sys.stderr,
                )
                for name, expected, actual in drift:
                    print(f"  {name}\n    index    {expected}\n    on disk  {actual}", file=sys.stderr)
                print(
                    "\nThe registry has been modified since index.json was generated. Run "
                    "`agtmls index --write` if the change is yours, or re-clone if it is not.",
                    file=sys.stderr,
                )
                return lockfile.EXIT_INTEGRITY_FAILURE

        rc = run(cmd, cwd=target)
        if rc != 0 or args.dry_run:
            return rc

        # Record what landed, so `agtmls verify` has something to check against.
        index = load_index()
        installed = installed_skill_names(target, args.agent)
        payload = lockfile.build(
            target, ROOT, installed,
            "copy" if args.copy else "symlink",
            str(index.get("registry_version", "")),
        )
        path = lockfile.write(target, payload)
        print(f"recorded {len(payload['skills'])} skill(s) in {path.relative_to(target)}")
        return 0
    if args.subcommand == "verify":
        return verify_install(args.target, args.agent, args.json)
    if args.subcommand == "uninstall":
        return uninstall(args.target, args.agent, args.remove_prompt)
    if args.subcommand == "propose-skill":
        return run(
            [
                sys.executable,
                str(ROOT / "scripts" / "propose-skill-from-session.py"),
                str(args.transcript),
                "--skill-name",
                args.skill_name,
            ]
        )
    if args.subcommand == "scaffold-skill":
        cmd = [sys.executable, str(ROOT / "scripts" / "scaffold-skill.py"), args.name]
        if args.bundle:
            cmd.extend(["--bundle", args.bundle])
        if args.title:
            cmd.extend(["--title", args.title])
        return run(cmd)
    return 2


if __name__ == "__main__":
    sys.exit(main())
