#!/usr/bin/env python3
"""Generate per-runtime plugin manifests from providers.json + plugin.json.

AgtMLS reaches agents three ways, and providers.json names all three:

  native_agents   symlink installs driven by setup-workspace.sh
  plugin_targets  runtimes with their own plugin manifest (this script)
  export_targets  Markdown bundles for runtimes with neither

Every manifest here is derived from `.claude-plugin/plugin.json` and the
skill tree, so a version bump or a new bundle cannot leave one runtime
behind. Hand-editing a generated manifest is a check failure.

  python3 scripts/generate-plugin-manifests.py --write
  python3 scripts/generate-plugin-manifests.py --check

Manifest shapes are taken from each runtime's own documentation, not
inferred: Antigravity wants `plugin.json` at the plugin root with its own
$schema (it does not read .claude-plugin/); `.agents/plugins/` is Codex
marketplace metadata; Gemini CLI reads `gemini-extension.json` plus a
context file of @-includes; OpenCode has no manifest and consumes an
`instructions` array in the user's opencode.json.

Because the skill tree is flat, every manifest points at a single
`./skills` path. That sidesteps the array-vs-string question entirely:
no runtime needs to support array-valued `skills` to see all 20 skills.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLUGIN = ROOT / ".claude-plugin" / "plugin.json"
PROVIDERS = ROOT / "providers.json"
SKILLS_DIR = ROOT / "skills"
ROUTER_SKILL = "skills/using-agtmls/SKILL.md"


def skill_paths() -> list[str]:
    """The skills root. Every runtime scans a `skills` path non-recursively
    for `<name>/SKILL.md`, which is exactly why the tree is flat: one string
    path works everywhere, including runtimes that reject an array."""
    return ["./skills"]


def agent_paths() -> list[str]:
    """Agent files, enumerated. `agents` takes an array of FILE paths, not a
    directory — verified against `claude plugin validate`, which rejects a
    directory string. Deriving it here means adding an agent cannot leave the
    manifests stale."""
    return sorted(
        "./" + p.relative_to(ROOT).as_posix()
        for p in (ROOT / "agents").glob("*.md")
    )


def dumps(data: object) -> str:
    return json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def base(plugin: dict[str, object]) -> dict[str, object]:
    return {
        "author": plugin["author"],
        "description": plugin["description"],
        "homepage": plugin["homepage"],
        "license": plugin["license"],
        "name": plugin["name"],
        "version": plugin["version"],
    }


def render(plugin: dict[str, object]) -> dict[str, str]:
    """Map every plugin target to its generated file content."""
    keywords = ["skills", "registry", "polyglot", "porting", "security", "release"]
    common = base(plugin)
    repo = plugin["homepage"]

    codex = {
        **common,
        "agents": agent_paths(),
        "commands": "./commands",
        "keywords": keywords,
        "repository": repo,
        "agents": agent_paths(),
        "skills": skill_paths(),
        "interface": {
            "displayName": "AgtMLS",
            "shortDescription": "The universal agent skills registry",
            "developerName": plugin["author"]["name"],
            "capabilities": ["Read", "Write", "Interactive"],
            "websiteURL": repo,
        },
    }
    cursor = {
        **common,
        "displayName": "AgtMLS",
        "keywords": keywords,
        "repository": repo,
        "agents": agent_paths(),
        "skills": skill_paths(),
    }
    kimi = {
        **common,
        "keywords": keywords,
        "sessionStart": {"skill": "using-agtmls"},
        "agents": agent_paths(),
        "skills": skill_paths(),
    }
    # Codex reads marketplace metadata from .agents/plugins/, not
    # .claude-plugin/. Same catalog, different location.
    agents_marketplace = {
        "name": plugin["name"],
        "interface": {"displayName": "AgtMLS"},
        "plugins": [
            {
                "category": "Developer Tools",
                "name": plugin["name"],
                "source": {"source": "url", "url": "./"},
            }
        ],
    }
    # Antigravity stages the directory it is pointed at and requires the
    # manifest at that directory's root.
    antigravity = {
        "$schema": "https://antigravity.google/schemas/v1/plugin.json",
        "description": plugin["description"],
        "name": plugin["name"],
    }
    gemini_extension = {
        "contextFileName": "GEMINI.md",
        "description": plugin["description"],
        "name": plugin["name"],
        "version": plugin["version"],
    }

    gemini_md = (
        "<!-- SPDX-FileCopyrightText: 2026 Sebastien Rousseau -->\n"
        "<!-- SPDX-License-Identifier: MIT -->\n"
        "<!-- Generated by scripts/generate-plugin-manifests.py; "
        "do not edit by hand. -->\n"
        f"@./{ROUTER_SKILL}\n"
    )

    opencode_install = f"""<!-- SPDX-FileCopyrightText: 2026 Sebastien Rousseau -->
<!-- SPDX-License-Identifier: MIT -->
<!-- Generated by scripts/generate-plugin-manifests.py; do not edit by hand. -->

# Installing AgtMLS for OpenCode

OpenCode has no plugin manifest for skill bundles. It loads Markdown
guidance through the `instructions` array in `opencode.json`, which takes
paths and glob patterns.

Clone the hub, then add it to your global or project `opencode.json`:

```json
{{
  "instructions": [
    "~/dev/agtmls/system-prompts/_base.md",
    "~/dev/agtmls/skills/*/SKILL.md"
  ]
}}
```

One glob covers the catalog: the skill tree is flat, so every skill is
exactly one level under `skills/`.

This loads every skill body eagerly, which spends context that a native
progressive-disclosure install would not. Prefer a narrower glob, or
export a profile and point `instructions` at that instead:

```sh
python3 scripts/agtmls.py export --provider generic --profile minimal --out-dir dist
```

Verify by asking OpenCode: "which AgtMLS skill applies here?"
"""

    return {
        ".agents/plugins/marketplace.json": dumps(agents_marketplace),
        ".codex-plugin/plugin.json": dumps(codex),
        ".cursor-plugin/plugin.json": dumps(cursor),
        ".kimi-plugin/plugin.json": dumps(kimi),
        ".opencode/INSTALL.md": opencode_install,
        "gemini-extension.json": dumps(gemini_extension),
        "GEMINI.md": gemini_md,
        "plugin.json": dumps(antigravity),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true", help="fail if any manifest is stale")
    group.add_argument("--write", action="store_true", help="regenerate manifests")
    args = parser.parse_args()

    plugin = json.loads(PLUGIN.read_text(encoding="utf-8"))
    providers = json.loads(PROVIDERS.read_text(encoding="utf-8"))
    targets = providers.get("plugin_targets", {})
    files = render(plugin)

    declared = {path for spec in targets.values() for path in spec.get("manifest_files", [])}
    if declared != set(files):
        print("FAIL: providers.json plugin_targets manifest_files do not match generated set")
        for path in sorted(declared ^ set(files)):
            print(f"    - {path}")
        return 1

    if not (ROOT / ROUTER_SKILL).exists():
        print(f"FAIL: router skill missing: {ROUTER_SKILL}")
        return 1

    stale: list[str] = []
    written = 0
    for rel, content in sorted(files.items()):
        path = ROOT / rel
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            written += 1
        else:
            stale.append(rel)

    if args.write:
        print(f"OK: {written} of {len(files)} plugin manifest(s) regenerated")
        return 0
    if stale:
        for rel in stale:
            print(f"FAIL: {rel} is stale")
        print()
        print(f"FAIL: {len(stale)} stale manifest(s); run generate-plugin-manifests.py --write")
        return 1
    print(f"OK: {len(files)} plugin manifest(s) current across {len(targets)} target(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
