#!/usr/bin/env python3
"""Generate CATALOG.md from index.json."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.json"
CATALOG = ROOT / "CATALOG.md"


def render() -> str:
    index = json.loads(INDEX.read_text(encoding="utf-8"))
    lines = [
        "<!-- SPDX-FileCopyrightText: 2026 Sebastien Rousseau -->",
        "<!-- SPDX-License-Identifier: MIT -->",
        "<!-- Generated by scripts/generate-catalog.py; do not edit by hand. -->",
        "",
        "# AgtMLS Catalog",
        "",
        f"Registry version: `{index['registry_version']}`",
        f"Skills: `{index['skill_count']}`",
        f"Commands: `{index['command_count']}`",
        "",
        "## Skills",
        "",
        "| Name | Bundle | Tags | Path |",
        "|---|---|---|---|",
    ]
    for skill in index["skills"]:
        bundle = skill["bundle"] or "general"
        tags = ", ".join(skill["tags"])
        lines.append(f"| `{skill['name']}` | `{bundle}` | {tags} | `{skill['path']}` |")
    lines.extend(["", "## Commands", "", "| Name | Description | Path |", "|---|---|---|"])
    for command in index["commands"]:
        lines.append(f"| `{command['name']}` | {command['description']} | `{command['path']}` |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.write:
        CATALOG.write_text(text, encoding="utf-8")
        print(f"wrote {CATALOG.relative_to(ROOT)}")
        return 0
    if args.check:
        current = CATALOG.read_text(encoding="utf-8") if CATALOG.exists() else ""
        if current != text:
            print("FAIL: CATALOG.md is missing or stale; run python3 scripts/generate-catalog.py --write")
            return 1
        print("OK: CATALOG.md is current")
        return 0
    print(text, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
