#!/usr/bin/env bash
# AgtMLS workspace setup script.
#
# Links the AgtMLS system prompt, skills, and slash commands into a
# target repository so a coding agent (Claude Code, Aider, Codex, ...)
# picks them up automatically. Runs from inside the target repo:
#
#   ~/dev/agtmls/scripts/setup-workspace.sh rust aider
#
# Design note — WHERE files must land to be AUTO-LOADED:
#   - The assembled system prompt goes to a REPO-ROOT file the tool
#     reads on its own (CLAUDE.md / AGENTS.md / CONVENTIONS.md). It must
#     NOT live inside the tool's dot-dir — no tool auto-reads
#     `.claude/AGENTS.md` or `.codex/AGENTS.md`.
#   - Skills are linked as LEAF directories (each containing a SKILL.md)
#     directly under `<cli>/skills/<skill>`. Runtimes scan that path
#     non-recursively, so anything two levels deep is undiscoverable — which
#     is why the hub's own skills/ tree is flat too.
set -euo pipefail

AGTMLS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
TARGET_DIR=$(pwd)
LANGUAGE=${1:-}
AGENT_CLI=${2:-}

# Flags:
#   --skills-only    link skills/commands WITHOUT writing a system prompt
#                    (source the prompt elsewhere, e.g. global ~/.claude/CLAUDE.md);
#                    also cleans up a prompt left by an earlier normal run.
#   --copy           copy skills instead of symlinking, for hubs that do not
#                    persist (an installed wheel under uvx/pipx).
#   --bundle <name>  additionally link skills whose metadata.json declares
#                    `"bundle": "<name>"` (e.g. `noyalib`). Repeatable. By
#                    default only GENERAL skills (bundle: null) are linked —
#                    a project's skills never land in an unrelated repo.
SKILLS_ONLY=false
BUNDLES=()
# Symlinks assume the hub stays put. An installed wheel (uvx/pipx) lives in an
# ephemeral cache, so --copy materialises real files instead of dangling links.
COPY=false
_args=("$@")
_i=0
while [[ $_i -lt ${#_args[@]} ]]; do
  case "${_args[$_i]}" in
    --skills-only) SKILLS_ONLY=true ;;
    --copy) COPY=true ;;
    --bundle)
      _i=$((_i + 1))
      [[ $_i -lt ${#_args[@]} ]] && BUNDLES+=("${_args[$_i]}")
      ;;
  esac
  _i=$((_i + 1))
done

if [[ -z "$LANGUAGE" || -z "$AGENT_CLI" ]]; then
  echo "Usage: $0 <language> <agent-cli> [--skills-only] [--copy] [--bundle <name>]..."
  echo "  language:      rust | python | go | cpp | swift | typescript | javascript | ruby | bash"
  echo "  agent-cli:     claude | aider | codex"
  echo "  --skills-only: link skills only; do not write a system prompt"
  echo "  --bundle NAME: also link the NAME project skill bundle (e.g. noyalib); repeatable"
  echo "  --copy:        copy skills instead of symlinking (for non-persistent hubs)"
  echo
  echo "Example: $0 rust claude"
  echo "Example: $0 python claude --skills-only"
  echo "Example: $0 rust claude --skills-only --bundle noyalib"
  exit 1
fi

mode_note=""
$SKILLS_ONLY && mode_note=" (skills-only)"
echo "🚀 Configuring AgtMLS workspace in $TARGET_DIR for $LANGUAGE using $AGENT_CLI$mode_note"

# 1. Map CLI tool to its dot-dir (skills/commands) and its AUTO-LOADED
#    system-prompt path (repo root — see design note above).
case "$AGENT_CLI" in
  claude) CLI_DIR=".claude"; SYS_PATH="CLAUDE.md" ;;
  aider)  CLI_DIR=".aider";  SYS_PATH="CONVENTIONS.md" ;;
  codex)  CLI_DIR=".codex";  SYS_PATH="AGENTS.md" ;;
  *)      CLI_DIR=".agent";  SYS_PATH="AGENTS.md" ;;
esac

mkdir -p "$TARGET_DIR/$CLI_DIR/skills"
mkdir -p "$TARGET_DIR/$CLI_DIR/commands"
mkdir -p "$TARGET_DIR/$CLI_DIR/agents"

# 2. Assemble the system prompt (base + language profile) at repo root —
#    unless --skills-only, in which case only clean up a prompt a previous
#    run generated (a hand-authored prompt with no marker is left untouched).
if $SKILLS_ONLY; then
  if [[ -f "$TARGET_DIR/$SYS_PATH" ]] && head -1 "$TARGET_DIR/$SYS_PATH" | grep -q "Generated by AgtMLS"; then
    rm -f "$TARGET_DIR/$SYS_PATH"
    echo "🧹 Removed the AgtMLS-generated $SYS_PATH (skills-only)"
  fi
else
  echo "📝 Assembling system prompt → $SYS_PATH (repo root, auto-loaded)"
  {
    echo "<!-- Generated by AgtMLS setup-workspace.sh — do not edit here."
    echo "     Edit the hub (system-prompts/_base.md + $LANGUAGE.md) and re-run. -->"
    echo
    cat "$AGTMLS_DIR/system-prompts/_base.md"
    printf '\n\n'
  } > "$TARGET_DIR/$SYS_PATH"

  if [[ -f "$AGTMLS_DIR/system-prompts/$LANGUAGE.md" ]]; then
    cat "$AGTMLS_DIR/system-prompts/$LANGUAGE.md" >> "$TARGET_DIR/$SYS_PATH"
  else
    echo "⚠️  Language profile '$LANGUAGE.md' not found in system-prompts/. Using base only."
  fi

  # 2a. Aider does not auto-read CONVENTIONS.md — register it so it loads.
  if [[ "$AGENT_CLI" == "aider" ]]; then
    CONF="$TARGET_DIR/.aider.conf.yml"
    if [[ ! -f "$CONF" ]] || ! grep -q 'CONVENTIONS.md' "$CONF" 2>/dev/null; then
      echo "🔧 Registering CONVENTIONS.md in .aider.conf.yml"
      printf 'read:\n  - CONVENTIONS.md\n' >> "$CONF"
    fi
  fi
fi

# 2b. Keep the generated prompt + CLI dir LOCAL and private. The assembled
#     prompt is a per-machine artifact of the hub, not repo content — commit
#     it and it drifts from the hub and leaks your personal config. Add it to
#     the target's .git/info/exclude (a personal, UN-committed ignore) so it
#     stays local and re-running never dirties the working tree. This does not
#     touch the committed .gitignore; skips gracefully outside a git repo.
GIT_DIR_PATH="$(git -C "$TARGET_DIR" rev-parse --absolute-git-dir 2>/dev/null || true)"
if [[ -n "$GIT_DIR_PATH" ]]; then
  EXCLUDE="$GIT_DIR_PATH/info/exclude"
  mkdir -p "$(dirname "$EXCLUDE")"
  ignore_local() { grep -qxF "$1" "$EXCLUDE" 2>/dev/null || printf '%s\n' "$1" >> "$EXCLUDE"; }
  unignore_local() {
    [[ -f "$EXCLUDE" ]] || return 0
    if grep -qxF "$1" "$EXCLUDE"; then
      grep -vxF "$1" "$EXCLUDE" > "$EXCLUDE.tmp" && mv "$EXCLUDE.tmp" "$EXCLUDE"
    fi
    return 0
  }
  ignore_local "$CLI_DIR/"
  if $SKILLS_ONLY; then
    # No prompt written — drop any stale prompt-ignore entries.
    unignore_local "$SYS_PATH"
    unignore_local ".aider.conf.yml"
    echo "🙈 Kept $CLI_DIR/ local (.git/info/exclude) — skills-only, no prompt"
  else
    ignore_local "$SYS_PATH"
    [[ "$AGENT_CLI" == "aider" ]] && ignore_local ".aider.conf.yml"
    echo "🙈 Kept $SYS_PATH + $CLI_DIR/ local (.git/info/exclude) — private, not committed"
  fi
fi

# 3. Symlink skills and commands so hub updates propagate instantly.
#    The skill tree is FLAT — every skill is skills/<name>/SKILL.md — because
#    each agent runtime scans its skills path non-recursively. Bundle
#    membership is the `bundle` field in each skill's metadata.json, not a
#    parent directory.
#    A GENERAL skill (bundle: null) is always linked; it applies anywhere.
#    A PROJECT skill is linked only when its bundle is named via --bundle, so
#    a project's skills never land in an unrelated repo.
link_or_copy() {
  local src=$1 dst=$2
  if $COPY; then
    rm -rf "$dst"
    cp -R "$src" "$dst"
  else
    ln -sfn "$src" "$dst"
  fi
}

if $COPY; then
  echo "📦 Copying skills and commands"
else
  echo "🔗 Linking skills and commands"
fi
linked=0
# python3 is already required by the rest of the toolchain (doctor, index,
# every check); reading one JSON field is not a new dependency.
while IFS=$'\t' read -r name bundle; do
  [[ -n "$name" ]] || continue
  entry="$AGTMLS_DIR/skills/$name"
  if [[ -z "$bundle" ]]; then
    want=true
  else
    want=false
    for b in "${BUNDLES[@]:-}"; do [[ "$b" == "$bundle" ]] && want=true; done
  fi
  if $want; then
    link_or_copy "$entry" "$TARGET_DIR/$CLI_DIR/skills/$name"
    linked=$((linked + 1))
  fi
done < <(python3 - "$AGTMLS_DIR" <<'PY'
import json, pathlib, sys
skills = pathlib.Path(sys.argv[1]) / "skills"
for skill_md in sorted(skills.glob("*/SKILL.md")):
    meta_path = skill_md.parent / "metadata.json"
    meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.exists() else {}
    print(f"{skill_md.parent.name}\t{meta.get('bundle') or ''}")
PY
)
for b in "${BUNDLES[@]:-}"; do [[ -n "$b" ]] && echo "   + bundle: $b"; done
if $COPY; then echo "   copied $linked skill(s)"; else echo "   linked $linked skill(s)"; fi

# Agents are subagent definitions; every native layout takes them beside
# skills and commands. They are general-purpose, so all of them link.
if compgen -G "$AGTMLS_DIR/agents/*.md" > /dev/null; then
  for entry in "$AGTMLS_DIR/agents/"*.md; do
    link_or_copy "$entry" "$TARGET_DIR/$CLI_DIR/agents/$(basename "$entry")"
  done
  echo "   + $(ls "$AGTMLS_DIR"/agents/*.md | wc -l | tr -d ' ') agent(s)"
fi

if compgen -G "$AGTMLS_DIR/commands/*" > /dev/null; then
  for entry in "$AGTMLS_DIR/commands/"*; do
    [[ -e "$entry" ]] || continue
    case "$(basename "$entry")" in
      README.md|.*) continue ;;
    esac
    link_or_copy "$entry" "$TARGET_DIR/$CLI_DIR/commands/$(basename "$entry")"
  done
else
  echo "   (no commands to link yet)"
fi

if $SKILLS_ONLY; then
  echo "✅ AgtMLS setup complete (skills-only): skills → $CLI_DIR/skills/. No system prompt written."
else
  echo "✅ AgtMLS setup complete: system prompt → $SYS_PATH, skills → $CLI_DIR/skills/."
fi
