#!/usr/bin/env bash
# AgtMLS workspace setup script.
#
# Links the AgtMLS system prompt, skills, and slash commands into a
# target repository so a coding agent (Claude Code, Aider, Codex, ...)
# picks them up automatically. Runs from inside the target repo:
#
#   ~/dev/agtmls/scripts/setup-workspace.sh rust aider
#
# Design note — WHERE files must land to be AUTO-LOADED:
#   - The assembled system prompt goes to a REPO-ROOT file the tool
#     reads on its own (CLAUDE.md / AGENTS.md / CONVENTIONS.md). It must
#     NOT live inside the tool's dot-dir — no tool auto-reads
#     `.claude/AGENTS.md` or `.codex/AGENTS.md`.
#   - Skills are linked as LEAF directories (each containing a SKILL.md)
#     directly under `<cli>/skills/<skill>`. A project bundle such as
#     `skills/noyalib/*` is flattened so each skill lands one level deep,
#     not two — `<cli>/skills/noyalib/<skill>` is too deep to discover.
set -euo pipefail

AGTMLS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
TARGET_DIR=$(pwd)
LANGUAGE=${1:-}
AGENT_CLI=${2:-}

if [[ -z "$LANGUAGE" || -z "$AGENT_CLI" ]]; then
  echo "Usage: $0 <language> <agent-cli>"
  echo "  language:  rust   (python | cpp | go | js: base-only until authored)"
  echo "  agent-cli: claude | aider | codex"
  echo
  echo "Example: $0 rust aider"
  echo "Example: $0 rust claude"
  exit 1
fi

echo "🚀 Configuring AgtMLS workspace in $TARGET_DIR for $LANGUAGE using $AGENT_CLI"

# 1. Map CLI tool to its dot-dir (skills/commands) and its AUTO-LOADED
#    system-prompt path (repo root — see design note above).
case "$AGENT_CLI" in
  claude) CLI_DIR=".claude"; SYS_PATH="CLAUDE.md" ;;
  aider)  CLI_DIR=".aider";  SYS_PATH="CONVENTIONS.md" ;;
  codex)  CLI_DIR=".codex";  SYS_PATH="AGENTS.md" ;;
  *)      CLI_DIR=".agent";  SYS_PATH="AGENTS.md" ;;
esac

mkdir -p "$TARGET_DIR/$CLI_DIR/skills"
mkdir -p "$TARGET_DIR/$CLI_DIR/commands"

# 2. Assemble the system prompt: base + language profile, at repo root.
echo "📝 Assembling system prompt → $SYS_PATH (repo root, auto-loaded)"
{
  echo "<!-- Generated by AgtMLS setup-workspace.sh — do not edit here."
  echo "     Edit the hub (system-prompts/_base.md + $LANGUAGE.md) and re-run. -->"
  echo
  cat "$AGTMLS_DIR/system-prompts/_base.md"
  printf '\n\n'
} > "$TARGET_DIR/$SYS_PATH"

if [[ -f "$AGTMLS_DIR/system-prompts/$LANGUAGE.md" ]]; then
  cat "$AGTMLS_DIR/system-prompts/$LANGUAGE.md" >> "$TARGET_DIR/$SYS_PATH"
else
  echo "⚠️  Language profile '$LANGUAGE.md' not found in system-prompts/. Using base only."
fi

# 2a. Aider does not auto-read CONVENTIONS.md — register it so it loads.
if [[ "$AGENT_CLI" == "aider" ]]; then
  CONF="$TARGET_DIR/.aider.conf.yml"
  if [[ ! -f "$CONF" ]] || ! grep -q 'CONVENTIONS.md' "$CONF" 2>/dev/null; then
    echo "🔧 Registering CONVENTIONS.md in .aider.conf.yml"
    printf 'read:\n  - CONVENTIONS.md\n' >> "$CONF"
  fi
fi

# 3. Symlink skills and commands so hub updates propagate instantly.
#    A skill is any directory that CONTAINS a SKILL.md. Bundles (a dir of
#    skill dirs, no top-level SKILL.md) are flattened one level.
echo "🔗 Linking skills and commands"
linked=0
for entry in "$AGTMLS_DIR/skills/"*; do
  [[ -d "$entry" ]] || continue
  if [[ -f "$entry/SKILL.md" ]]; then
    ln -sfn "$entry" "$TARGET_DIR/$CLI_DIR/skills/$(basename "$entry")"
    linked=$((linked + 1))
  else
    for leaf in "$entry"/*; do
      [[ -f "$leaf/SKILL.md" ]] || continue
      ln -sfn "$leaf" "$TARGET_DIR/$CLI_DIR/skills/$(basename "$leaf")"
      linked=$((linked + 1))
    done
  fi
done
echo "   linked $linked skill(s)"

if compgen -G "$AGTMLS_DIR/commands/*" > /dev/null; then
  for entry in "$AGTMLS_DIR/commands/"*; do
    [[ -e "$entry" ]] || continue
    ln -sfn "$entry" "$TARGET_DIR/$CLI_DIR/commands/$(basename "$entry")"
  done
else
  echo "   (no commands to link yet)"
fi

echo "✅ AgtMLS setup complete: system prompt → $SYS_PATH, skills → $CLI_DIR/skills/."
