#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Sebastien Rousseau
# SPDX-License-Identifier: Apache-2.0 OR MIT
"""Prove `agtmls install` never destroys a prompt file it did not write.

setup-workspace.sh used to truncate the target's CLAUDE.md / AGENTS.md /
CONVENTIONS.md unconditionally. A user with a hand-authored prompt lost it
with no warning, no backup, and -- if the file was untracked -- no recovery.
The removal path had always checked for the "Generated by AgtMLS" marker;
only the write path did not.

Every case below is a property the installer must hold for any consumer repo.
"""

from __future__ import annotations

import filecmp
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLI = ROOT / "scripts" / "agtmls.py"
OWN_CONTENT = "# My own instructions\nHand written. Do not clobber.\n"


def install(target: Path, *flags: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(CLI), "install", "rust", "claude", "--target", str(target), *flags],
        cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False,
    )


def fresh(tmp: Path, name: str) -> Path:
    target = tmp / name
    target.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=target, check=True)
    (target / "CLAUDE.md").write_text(OWN_CONTENT, encoding="utf-8")
    return target


def main() -> int:
    errors: list[str] = []
    with tempfile.TemporaryDirectory() as raw:
        tmp = Path(raw)
        pristine = tmp / "pristine.md"
        pristine.write_text(OWN_CONTENT, encoding="utf-8")

        # 1. A foreign prompt file must abort the install, before any mutation.
        target = fresh(tmp, "refuse")
        proc = install(target)
        if proc.returncode == 0:
            errors.append(f"install overwrote a foreign prompt file:\n{proc.stdout}")
        if not filecmp.cmp(target / "CLAUDE.md", pristine, shallow=False):
            errors.append("install modified a prompt file it did not generate")
        if (target / ".claude").exists():
            errors.append("install mutated the target before refusing")

        # 2. --dry-run must describe everything and change nothing.
        target = fresh(tmp, "dryrun")
        proc = install(target, "--force", "--dry-run")
        if proc.returncode != 0:
            errors.append(f"--dry-run failed:\n{proc.stdout}")
        if "[dry-run]" not in proc.stdout:
            errors.append("--dry-run produced no plan")
        if not filecmp.cmp(target / "CLAUDE.md", pristine, shallow=False):
            errors.append("--dry-run modified the prompt file")
        if (target / ".claude").exists():
            errors.append("--dry-run created directories")
        if list(target.glob("CLAUDE.md.agtmls-backup.*")):
            errors.append("--dry-run created a backup file")

        # 3. --force must back the file up byte-for-byte, then overwrite.
        target = fresh(tmp, "force")
        proc = install(target, "--force")
        if proc.returncode != 0:
            errors.append(f"--force install failed:\n{proc.stdout}")
        backups = list(target.glob("CLAUDE.md.agtmls-backup.*"))
        if len(backups) != 1:
            errors.append(f"expected exactly one backup, found {len(backups)}")
        elif not filecmp.cmp(backups[0], pristine, shallow=False):
            errors.append("backup does not match the original content")
        if "Generated by AgtMLS" not in (target / "CLAUDE.md").read_text(encoding="utf-8"):
            errors.append("--force did not write the generated prompt")

        # 4. Re-running over our own generated prompt is idempotent: no backup.
        proc = install(target)
        if proc.returncode != 0:
            errors.append(f"re-install over a generated prompt failed:\n{proc.stdout}")
        if len(list(target.glob("CLAUDE.md.agtmls-backup.*"))) != 1:
            errors.append("re-install backed up a file AgtMLS itself generated")

        # 5. --skills-only must never touch a foreign prompt file.
        target = fresh(tmp, "skillsonly")
        proc = install(target, "--skills-only")
        if proc.returncode != 0:
            errors.append(f"--skills-only failed:\n{proc.stdout}")
        if not filecmp.cmp(target / "CLAUDE.md", pristine, shallow=False):
            errors.append("--skills-only removed a prompt file it did not generate")

        # 6. An unknown agent must fail loudly, not install somewhere unread.
        target = tmp / "unknown"
        target.mkdir()
        proc = subprocess.run(
            [str(ROOT / "scripts" / "setup-workspace.sh"), "rust", "nosuchagent"],
            cwd=target, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False,
        )
        if proc.returncode == 0 or (target / ".agent").exists():
            errors.append("unknown agent silently installed into an unread directory")

    if errors:
        for error in errors:
            print(f"FAIL: {error}")
        print()
        print(f"FAIL: {len(errors)} install-safety issue(s)")
        return 1
    print("OK: install refuses to destroy user prompt files (6 properties)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
