#!/usr/bin/env python3
"""Smoke-test setup-workspace.sh in temporary consumer repos."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SETUP = ROOT / "scripts" / "setup-workspace.sh"


def run(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=cwd,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )


def expect(condition: bool, message: str, errors: list[str]) -> None:
    if not condition:
        errors.append(message)


def smoke_skills_only(tmp: Path, errors: list[str]) -> None:
    target = tmp / "skills-only"
    target.mkdir()
    proc = run([str(SETUP), "rust", "codex", "--skills-only", "--bundle", "noyalib"], target)
    expect(proc.returncode == 0, f"skills-only setup failed:\n{proc.stdout}", errors)
    expect((target / ".codex" / "skills" / "cross-language-port").is_symlink(), "missing general skill link", errors)
    expect((target / ".codex" / "skills" / "noyalib-ci-and-release").is_symlink(), "missing bundle skill link", errors)
    expect((target / ".codex" / "commands" / "agtmls.md").is_symlink(), "missing command link", errors)
    expect(not (target / ".codex" / "commands" / "README.md").exists(), "README.md was installed as a command", errors)
    expect(not (target / "AGENTS.md").exists(), "skills-only run wrote AGENTS.md", errors)


def smoke_prompt(tmp: Path, errors: list[str]) -> None:
    target = tmp / "prompt"
    target.mkdir()
    proc = run([str(SETUP), "python", "claude"], target)
    expect(proc.returncode == 0, f"prompt setup failed:\n{proc.stdout}", errors)
    prompt = target / "CLAUDE.md"
    expect(prompt.exists(), "normal setup did not write CLAUDE.md", errors)
    if prompt.exists():
        first = prompt.read_text(encoding="utf-8").splitlines()[:1]
        expect(bool(first and "Generated by AgtMLS" in first[0]), "CLAUDE.md missing generated marker", errors)
    expect((target / ".claude" / "skills" / "using-agtmls").is_symlink(), "missing using-agtmls skill link", errors)


def main() -> int:
    errors: list[str] = []
    with tempfile.TemporaryDirectory(prefix="agtmls-smoke-") as td:
        tmp = Path(td)
        smoke_skills_only(tmp, errors)
        smoke_prompt(tmp, errors)
    if errors:
        for error in errors:
            print(f"FAIL: {error}")
        print()
        print(f"FAIL: {len(errors)} install smoke issue(s)")
        return 1
    print("OK: setup-workspace smoke install passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
