#!/usr/bin/env python3
"""Validate generated artifact provenance markers."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main() -> int:
    errors: list[str] = []
    index = json.loads((ROOT / "index.json").read_text(encoding="utf-8"))
    if index.get("generated_by") != "scripts/generate-skill-index.py":
        errors.append("index.json generated_by is wrong")
    catalog = (ROOT / "CATALOG.md").read_text(encoding="utf-8")
    if "Generated by scripts/generate-catalog.py; do not edit by hand." not in catalog:
        errors.append("CATALOG.md missing generated marker")
    if "Do not edit `index.json` manually" not in (ROOT / "references" / "registry-schema.md").read_text(encoding="utf-8"):
        errors.append("registry schema missing index no-manual-edit rule")
    if "do not edit index.json by hand" not in (ROOT / "lifecycle.json").read_text(encoding="utf-8"):
        errors.append("lifecycle metadata missing index no-manual-edit rule")
    if errors:
        for error in errors:
            print(f"FAIL: {error}")
        print()
        print(f"FAIL: {len(errors)} generated artifact issue(s)")
        return 1
    print("OK: generated artifact provenance valid")
    return 0


if __name__ == "__main__":
    sys.exit(main())
