# fish completion for agtmls
# SPDX-FileCopyrightText: 2026 Sebastien Rousseau
# SPDX-License-Identifier: Apache-2.0 OR MIT

complete -c agtmls -f
complete -c agtmls -n "__fish_use_subcommand" -a "agent-card" -d "agent-card command"
complete -c agtmls -n "__fish_use_subcommand" -a "audit" -d "audit command"
complete -c agtmls -n "__fish_use_subcommand" -a "bench" -d "bench command"
complete -c agtmls -n "__fish_use_subcommand" -a "bump-version" -d "bump-version command"
complete -c agtmls -n "__fish_use_subcommand" -a "check" -d "check command"
complete -c agtmls -n "__fish_use_subcommand" -a "diff" -d "diff command"
complete -c agtmls -n "__fish_use_subcommand" -a "docs-site" -d "docs-site command"
complete -c agtmls -n "__fish_use_subcommand" -a "doctor" -d "doctor command"
complete -c agtmls -n "__fish_use_subcommand" -a "evidence" -d "evidence command"
complete -c agtmls -n "__fish_use_subcommand" -a "evolve" -d "evolve command"
complete -c agtmls -n "__fish_use_subcommand" -a "export" -d "export command"
complete -c agtmls -n "__fish_use_subcommand" -a "import-skill" -d "import-skill command"
complete -c agtmls -n "__fish_use_subcommand" -a "index" -d "index command"
complete -c agtmls -n "__fish_use_subcommand" -a "install" -d "install command"
complete -c agtmls -n "__fish_use_subcommand" -a "list" -d "list command"
complete -c agtmls -n "__fish_use_subcommand" -a "mcp-resources" -d "mcp-resources command"
complete -c agtmls -n "__fish_use_subcommand" -a "next-version" -d "next-version command"
complete -c agtmls -n "__fish_use_subcommand" -a "plugin-manifests" -d "plugin-manifests command"
complete -c agtmls -n "__fish_use_subcommand" -a "profiles" -d "profiles command"
complete -c agtmls -n "__fish_use_subcommand" -a "propose-skill" -d "propose-skill command"
complete -c agtmls -n "__fish_use_subcommand" -a "provenance" -d "provenance command"
complete -c agtmls -n "__fish_use_subcommand" -a "provider-install" -d "provider-install command"
complete -c agtmls -n "__fish_use_subcommand" -a "providers" -d "providers command"
complete -c agtmls -n "__fish_use_subcommand" -a "release-check" -d "release-check command"
complete -c agtmls -n "__fish_use_subcommand" -a "release-dry-run" -d "release-dry-run command"
complete -c agtmls -n "__fish_use_subcommand" -a "release-pack" -d "release-pack command"
complete -c agtmls -n "__fish_use_subcommand" -a "sbom" -d "sbom command"
complete -c agtmls -n "__fish_use_subcommand" -a "scaffold-skill" -d "scaffold-skill command"
complete -c agtmls -n "__fish_use_subcommand" -a "search" -d "search command"
complete -c agtmls -n "__fish_use_subcommand" -a "show" -d "show command"
complete -c agtmls -n "__fish_use_subcommand" -a "stats" -d "stats command"
complete -c agtmls -n "__fish_use_subcommand" -a "status" -d "status command"
complete -c agtmls -n "__fish_use_subcommand" -a "uninstall" -d "uninstall command"
complete -c agtmls -n "__fish_use_subcommand" -a "verify-release-assets" -d "verify-release-assets command"
